bfl::SUKFCorrection Class Reference
This class implements the algorithm: Barfoot, T., McManus, C.
#include <SUKFCorrection.h>
Public Member Functions
SUKFCorrection (std::unique_ptr< AdditiveMeasurementModel > measurement_model, const std::size_t state_size, const double alpha, const double beta, const double kappa, const std::size_t measurement_sub_size) noexcept
The input argument meas_sub_size is the sub-size, J, of the measurement vector y in R^M such that M = k * J for some positive integer k.
SUKFCorrection (std::unique_ptr< AdditiveMeasurementModel > measurement_model, const std::size_t state_size, const double alpha, const double beta, const double kappa, const std::size_t measurement_sub_size, const bool use_reduced_noise_covariance_matrix) noexcept
If input argument use_reduced_noise_covariance_matrix is set to true, when the algorithm calls measurement_model_.getNoiseCovarianceMatrix() it expects to receive a noise covariance matrix of size measurement_sub_size_ x measurement_sub_size_ and uses it for all the sub-vectors beloning to the current measurement.
SUKFCorrection (SUKFCorrection &&sukf_correction) noexcept
virtual ~SUKFCorrection () noexcept
MeasurementModel & getMeasurementModel () override
void correct (const GaussianMixture &pred_state, GaussianMixture &corr_state)
bool skip (const bool status)
virtual std::pair< bool, Eigen::VectorXd > getLikelihood ()
Protected Member Functions
void correctStep (const GaussianMixture &pred_state, GaussianMixture &corr_state) override
std::pair< bool, Eigen::VectorXd > likelihood (const Eigen::Ref< const Eigen::MatrixXd > &innovations) override
Eigen::MatrixXd getNoiseCovarianceMatrix (const std::size_t index)
Private Attributes
std::unique_ptr< MeasurementModel > measurement_model_
bfl::sigma_point::UTWeight ut_weight_
Unscented transform weight.
std::size_t measurement_sub_size_
bool use_reduced_noise_covariance_matrix_
Detailed Description
This class implements the algorithm: Barfoot, T., McManus, C.
(2011), 'A Serial Approach to Handling High-Dimensional Measurements in the Sigma-Point Kalman Filter.', Science and Systems VII, MIT Press
Definition at line 23 of file SUKFCorrection.h.
Constructor & Destructor Documentation
SUKFCorrection() [1/3]
bfl::SUKFCorrection::SUKFCorrection (std::unique_ptr< AdditiveMeasurementModel > measurement_model, const std::size_t state_size, const double alpha, const double beta, const double kappa, const std::size_t measurement_sub_size) [noexcept]
The input argument meas_sub_size is the sub-size, J, of the measurement vector y in R^M such that M = k * J for some positive integer k.
SUKFCorrection() [2/3]
bfl::SUKFCorrection::SUKFCorrection (std::unique_ptr< AdditiveMeasurementModel > measurement_model, const std::size_t state_size, const double alpha, const double beta, const double kappa, const std::size_t measurement_sub_size, const bool use_reduced_noise_covariance_matrix) [noexcept]
If input argument use_reduced_noise_covariance_matrix is set to true, when the algorithm calls measurement_model_.getNoiseCovarianceMatrix() it expects to receive a noise covariance matrix of size measurement_sub_size_ x measurement_sub_size_ and uses it for all the sub-vectors beloning to the current measurement.
If set to false, the algorithms expects to receive the complete noise covariance matrix consisting in (M / meas_sub_size) diagonal blocks of size measurement_sub_size_ x measurement_sub_size_ where M is the size of the current measurement.
SUKFCorrection() [3/3]
SUKFCorrection::SUKFCorrection (SUKFCorrection && sukf_correction) [noexcept]
Definition at line 40 of file SUKFCorrection.cpp.
 SUKFCorrection()
virtual bfl::SUKFCorrection::~SUKFCorrection () [inline], [virtual], [noexcept]
Definition at line 45 of file SUKFCorrection.h.
Member Function Documentation
correct()
void GaussianCorrection::correct (const GaussianMixture & pred_state, GaussianMixture & corr_state) [inherited]
Definition at line 10 of file GaussianCorrection.cpp.
correctStep()
void SUKFCorrection::correctStep (const GaussianMixture & pred_state, GaussianMixture & corr_state) [override], [protected], [virtual]
Implements bfl::GaussianCorrection.
Definition at line 54 of file SUKFCorrection.cpp.
References bfl::any::any_cast(), bfl::GaussianMixture::components, bfl::GaussianMixture::covariance(), bfl::GaussianMixture::dim, bfl::GaussianMixture::dim_circular, bfl::GaussianMixture::dim_linear, bfl::directional_statistics::directional_sub(), bfl::GaussianMixture::mean(), and bfl::sigma_point::sigma_point().
getLikelihood()
std::pair< bool, VectorXd > GaussianCorrection::getLikelihood () [virtual], [inherited]
Definition at line 20 of file GaussianCorrection.cpp.
getMeasurementModel()
MeasurementModel & SUKFCorrection::getMeasurementModel () [override], [virtual]
Implements bfl::GaussianCorrection.
Definition at line 48 of file SUKFCorrection.cpp.
getNoiseCovarianceMatrix()
MatrixXd SUKFCorrection::getNoiseCovarianceMatrix (const std::size_t index) [protected]
Definition at line 169 of file SUKFCorrection.cpp.
likelihood()
std::pair< bool, Eigen::VectorXd > SUKFCorrection::likelihood (const Eigen::Ref< const Eigen::MatrixXd > & innovations) [override], [protected], [virtual]
Implements bfl::GaussianCorrection.
Definition at line 182 of file SUKFCorrection.cpp.
skip()
bool GaussianCorrection::skip (const bool status) [inherited]
Definition at line 26 of file GaussianCorrection.cpp.
Member Data Documentation
measurement_model_
std::unique_ptr<MeasurementModel> bfl::SUKFCorrection::measurement_model_ [private]
Definition at line 57 of file SUKFCorrection.h.
measurement_sub_size_
std::size_t bfl::SUKFCorrection::measurement_sub_size_ [private]
Definition at line 64 of file SUKFCorrection.h.
use_reduced_noise_covariance_matrix_
bool bfl::SUKFCorrection::use_reduced_noise_covariance_matrix_ [private]
Definition at line 66 of file SUKFCorrection.h.
ut_weight_
bfl::sigma_point::UTWeight bfl::SUKFCorrection::ut_weight_ [private]
Unscented transform weight.
Definition at line 62 of file SUKFCorrection.h.
The documentation for this class was generated from the following files:
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/include/BayesFilters/SUKFCorrection.h
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/src/SUKFCorrection.cpp