bfl::ParticleFilter Class Reference
#include <ParticleFilter.h>
Public Member Functions
virtual bool skip (const std::string &what_step, const bool status) override
bool boot ()
void run ()
bool wait ()
void reset ()
void reboot ()
bool teardown ()
unsigned int getFilteringStep ()
bool isRunning ()
bool enable_log (const std::string &prefix_path, const std::string &prefix_name)
bool disable_log ()
std::string get_prefix_path () const
std::string get_prefix_name () const
template<typename DatumType >
void logger (DatumType datum)
template<typename... DataType>
void logger (DataType... data)
template<typename DatumType >
void logger (DatumType datum) const
template<typename... DataType>
void logger (DataType... data) const
Protected Member Functions
ParticleFilter (std::unique_ptr< ParticleSetInitialization > initialization, std::unique_ptr< PFPrediction > prediction, std::unique_ptr< PFCorrection > correction, std::unique_ptr< Resampling > resampling) noexcept
virtual ~ParticleFilter () noexcept
ParticleFilter (ParticleFilter &&pf) noexcept
ParticleFilter & operator= (ParticleFilter &&pf) noexcept
virtual bool initialization ()=0
virtual void filteringStep ()=0
virtual bool runCondition ()=0
virtual std::vector< std::string > log_filenames (const std::string &prefix_path, const std::string &prefix_name)
virtual void log ()
Protected Attributes
std::unique_ptr< ParticleSetInitialization > initialization_
std::unique_ptr< PFPrediction > prediction_
std::unique_ptr< PFCorrection > correction_
std::unique_ptr< Resampling > resampling_
Detailed Description
Definition at line 17 of file ParticleFilter.h.
Constructor & Destructor Documentation
ParticleFilter() [1/2]
ParticleFilter::ParticleFilter (std::unique_ptr< ParticleSetInitialization > initialization, std::unique_ptr< PFPrediction > prediction, std::unique_ptr< PFCorrection > correction, std::unique_ptr< Resampling > resampling) [protected], [noexcept]
Definition at line 7 of file ParticleFilter.cpp.
 ParticleFilter()
ParticleFilter::~ParticleFilter () [protected], [virtual], [noexcept]
Definition at line 21 of file ParticleFilter.cpp.
ParticleFilter() [2/2]
ParticleFilter::ParticleFilter (ParticleFilter && pf) [protected], [noexcept]
Definition at line 25 of file ParticleFilter.cpp.
Member Function Documentation
boot()
bool FilteringAlgorithm::boot () [inherited]
Definition at line 8 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::filtering_thread_, and bfl::FilteringAlgorithm::filteringRecursion().
disable_log()
bool Logger::disable_log () [inherited]
Definition at line 58 of file Logger.cpp.
References bfl::Logger::file_names_, bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
Referenced by bfl::Logger::~Logger().
enable_log()
bool Logger::enable_log (const std::string & prefix_path, const std::string & prefix_name) [inherited]
Definition at line 15 of file Logger.cpp.
References bfl::Logger::file_names_, bfl::Logger::log_enabled_, bfl::Logger::log_filenames(), and bfl::Logger::log_files_.
filteringStep()
virtual void bfl::FilteringAlgorithm::filteringStep () [protected], [pure virtual], [inherited]
Implemented in bfl::SIS, bfl::GaussianFilter, and bfl::UnscentedKalmanFilter.
Referenced by bfl::FilteringAlgorithm::filteringRecursion().
get_prefix_name()
std::string Logger::get_prefix_name () const [inherited]
Definition at line 81 of file Logger.cpp.
References bfl::Logger::prefix_name_.
get_prefix_path()
std::string Logger::get_prefix_path () const [inherited]
Definition at line 75 of file Logger.cpp.
References bfl::Logger::prefix_path_.
getFilteringStep()
unsigned int FilteringAlgorithm::getFilteringStep () [inherited]
Definition at line 83 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::filtering_step_.
initialization()
virtual bool bfl::FilteringAlgorithm::initialization () [protected], [pure virtual], [inherited]
Implemented in bfl::SIS, bfl::GaussianFilter, and bfl::UnscentedKalmanFilter.
Referenced by bfl::FilteringAlgorithm::filteringRecursion().
isRunning()
bool FilteringAlgorithm::isRunning () [inherited]
Definition at line 89 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::run_.
log()
void Logger::log () [protected], [virtual], [inherited]
Reimplemented in bfl::SIS, bfl::SimulatedStateModel, and bfl::SimulatedLinearSensor.
Definition at line 99 of file Logger.cpp.
Referenced by bfl::GaussianFilter::filteringStep().
log_filenames()
std::vector< std::string > Logger::log_filenames (const std::string & prefix_path, const std::string & prefix_name) [protected], [virtual], [inherited]
Reimplemented in bfl::LinearModel, bfl::SimulatedStateModel, and bfl::SIS.
Definition at line 87 of file Logger.cpp.
Referenced by bfl::Logger::enable_log().
logger() [1/4]
template<typename DatumType >
void bfl::Logger::logger (DatumType datum) [inline], [inherited]
Definition at line 28 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
Referenced by bfl::SimulatedLinearSensor::log().
logger() [2/4]
template<typename... DataType>
void bfl::Logger::logger (DataType... data) [inline], [inherited]
Definition at line 35 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::logger_helper().
logger() [3/4]
template<typename DatumType >
void bfl::Logger::logger (DatumType datum) const [inline], [inherited]
Definition at line 42 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
logger() [4/4]
template<typename... DataType>
void bfl::Logger::logger (DataType... data) const [inline], [inherited]
Definition at line 49 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::logger_helper().
operator=()
ParticleFilter & ParticleFilter::operator= (ParticleFilter && pf) [protected], [noexcept]
Definition at line 33 of file ParticleFilter.cpp.
Referenced by bfl::SIS::operator=().
reboot()
void FilteringAlgorithm::reboot () [inherited]
Definition at line 66 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::cv_run_, bfl::FilteringAlgorithm::mtx_run_, bfl::FilteringAlgorithm::reset_, and bfl::FilteringAlgorithm::run_.
reset()
void FilteringAlgorithm::reset () [inherited]
Definition at line 60 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::reset_.
run()
void FilteringAlgorithm::run () [inherited]
Definition at line 26 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::cv_run_, bfl::FilteringAlgorithm::mtx_run_, and bfl::FilteringAlgorithm::run_.
runCondition()
virtual bool bfl::FilteringAlgorithm::runCondition () [protected], [pure virtual], [inherited]
Implemented in bfl::SIS, and bfl::GaussianFilter.
Referenced by bfl::FilteringAlgorithm::filteringRecursion().
skip()
bool ParticleFilter::skip (const std::string & what_step, const bool status) [override], [virtual]
Implements bfl::FilteringAlgorithm.
Definition at line 44 of file ParticleFilter.cpp.
References correction_, and prediction_.
teardown()
bool FilteringAlgorithm::teardown () [inherited]
Definition at line 75 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::teardown_.
wait()
bool FilteringAlgorithm::wait () [inherited]
Definition at line 34 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::filtering_thread_.
Member Data Documentation
correction_
std::unique_ptr<PFCorrection> bfl::ParticleFilter::correction_ [protected]
Definition at line 35 of file ParticleFilter.h.
Referenced by skip().
initialization_
std::unique_ptr<ParticleSetInitialization> bfl::ParticleFilter::initialization_ [protected]
Definition at line 31 of file ParticleFilter.h.
prediction_
std::unique_ptr<PFPrediction> bfl::ParticleFilter::prediction_ [protected]
Definition at line 33 of file ParticleFilter.h.
Referenced by skip().
resampling_
std::unique_ptr<Resampling> bfl::ParticleFilter::resampling_ [protected]
Definition at line 37 of file ParticleFilter.h.
The documentation for this class was generated from the following files:
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/include/BayesFilters/ParticleFilter.h
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/src/ParticleFilter.cpp