bfl::UKFCorrection Class Reference
#include <UKFCorrection.h>
Public Member Functions
UKFCorrection (std::unique_ptr< bfl::MeasurementModel > meas_model, const size_t n, const double alpha, const double beta, const double kappa) noexcept
UKFCorrection (std::unique_ptr< bfl::AdditiveMeasurementModel > meas_model, const size_t n, const double alpha, const double beta, const double kappa) noexcept
UKFCorrection (UKFCorrection &&ukf_prediction) noexcept
virtual ~UKFCorrection () noexcept
MeasurementModel & getMeasurementModel () override
void correct (const GaussianMixture &pred_state, GaussianMixture &corr_state)
bool skip (const bool status)
virtual std::pair< bool, Eigen::VectorXd > getLikelihood ()
Protected Types
enum UKFCorrectionType { UKFCorrectionType::Generic,
UKFCorrectionType::Additive
 }
Protected Member Functions
void correctStep (const bfl::GaussianMixture &pred_state, bfl::GaussianMixture &corr_state) override
std::pair< bool, Eigen::VectorXd > likelihood (const Eigen::Ref< const Eigen::MatrixXd > &innovations) override
Protected Attributes
std::unique_ptr< bfl::MeasurementModel > measurement_model_
std::unique_ptr< bfl::AdditiveMeasurementModel > additive_measurement_model_
UKFCorrectionType type_
Distinguish between a UKFCorrection using a generic MeasurmentModel and a UKFCorrection using an AdditiveMeasurementModel.
bfl::sigma_point::UTWeight ut_weight_
Unscented transform weight.
Detailed Description
Definition at line 17 of file UKFCorrection.h.
Member Enumeration Documentation
UKFCorrectionType
enum bfl::UKFCorrection::UKFCorrectionType [strong], [protected]
Enumerator
Generic
Additive
Definition at line 39 of file UKFCorrection.h.
Constructor & Destructor Documentation
UKFCorrection() [1/3]
bfl::UKFCorrection::UKFCorrection (std::unique_ptr< bfl::MeasurementModel > meas_model, const size_t n, const double alpha, const double beta, const double kappa) [noexcept]
UKFCorrection() [2/3]
bfl::UKFCorrection::UKFCorrection (std::unique_ptr< bfl::AdditiveMeasurementModel > meas_model, const size_t n, const double alpha, const double beta, const double kappa) [noexcept]
UKFCorrection() [3/3]
UKFCorrection::UKFCorrection (UKFCorrection && ukf_prediction) [noexcept]
Definition at line 36 of file UKFCorrection.cpp.
 UKFCorrection()
UKFCorrection::~UKFCorrection () [virtual], [noexcept]
Definition at line 44 of file UKFCorrection.cpp.
Member Function Documentation
correct()
void GaussianCorrection::correct (const GaussianMixture & pred_state, GaussianMixture & corr_state) [inherited]
Definition at line 10 of file GaussianCorrection.cpp.
correctStep()
void UKFCorrection::correctStep (const bfl::GaussianMixture & pred_state, bfl::GaussianMixture & corr_state) [override], [protected], [virtual]
Implements bfl::GaussianCorrection.
Definition at line 57 of file UKFCorrection.cpp.
References bfl::any::any_cast(), bfl::GaussianMixture::augmentWithNoise(), bfl::GaussianMixture::components, bfl::GaussianMixture::covariance(), bfl::MeasurementModel::getNoiseCovarianceMatrix(), bfl::MeasurementModel::getOutputSize(), bfl::MeasurementModel::innovation(), bfl::GaussianMixture::mean(), bfl::MeasurementModel::measure(), and bfl::sigma_point::unscented_transform().
getLikelihood()
std::pair< bool, VectorXd > GaussianCorrection::getLikelihood () [virtual], [inherited]
Definition at line 20 of file GaussianCorrection.cpp.
getMeasurementModel()
MeasurementModel & UKFCorrection::getMeasurementModel () [override], [virtual]
Implements bfl::GaussianCorrection.
Definition at line 48 of file UKFCorrection.cpp.
likelihood()
std::pair< bool, Eigen::VectorXd > UKFCorrection::likelihood (const Eigen::Ref< const Eigen::MatrixXd > & innovations) [override], [protected], [virtual]
Implements bfl::GaussianCorrection.
Definition at line 139 of file UKFCorrection.cpp.
skip()
bool GaussianCorrection::skip (const bool status) [inherited]
Definition at line 26 of file GaussianCorrection.cpp.
Member Data Documentation
additive_measurement_model_
std::unique_ptr<bfl::AdditiveMeasurementModel> bfl::UKFCorrection::additive_measurement_model_ [protected]
Definition at line 37 of file UKFCorrection.h.
measurement_model_
std::unique_ptr<bfl::MeasurementModel> bfl::UKFCorrection::measurement_model_ [protected]
Definition at line 35 of file UKFCorrection.h.
type_
UKFCorrectionType bfl::UKFCorrection::type_ [protected]
Distinguish between a UKFCorrection using a generic MeasurmentModel and a UKFCorrection using an AdditiveMeasurementModel.
Definition at line 45 of file UKFCorrection.h.
ut_weight_
bfl::sigma_point::UTWeight bfl::UKFCorrection::ut_weight_ [protected]
Unscented transform weight.
Definition at line 50 of file UKFCorrection.h.
The documentation for this class was generated from the following files:
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/include/BayesFilters/UKFCorrection.h
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/src/UKFCorrection.cpp