bfl::LTIMeasurementModel Class Reference
#include <LTIMeasurementModel.h>
Public Member Functions
LTIMeasurementModel (const Eigen::Ref< const Eigen::MatrixXd > &measurement_matrix, const Eigen::Ref< const Eigen::MatrixXd > &noise_covariance_matrix)
virtual ~LTIMeasurementModel () noexcept
std::pair< bool, Eigen::MatrixXd > getNoiseCovarianceMatrix () const override
Eigen::MatrixXd getMeasurementMatrix () const override
virtual std::pair< bool, bfl::Data > predictedMeasure (const Eigen::Ref< const Eigen::MatrixXd > &cur_states) const override
virtual std::pair< bool, bfl::Data > innovation (const bfl::Data &predicted_measurements, const bfl::Data &measurements) const override
virtual std::pair< bool, bfl::Data > measure () const =0
virtual bool setProperty (const std::string &property)
virtual bool freezeMeasurements ()=0
virtual std::pair< std::size_t, std::size_t > getOutputSize () const =0
bool enable_log (const std::string &prefix_path, const std::string &prefix_name)
bool disable_log ()
std::string get_prefix_path () const
std::string get_prefix_name () const
template<typename DatumType >
void logger (DatumType datum)
template<typename... DataType>
void logger (DataType... data)
template<typename DatumType >
void logger (DatumType datum) const
template<typename... DataType>
void logger (DataType... data) const
Protected Member Functions
virtual std::vector< std::string > log_filenames (const std::string &prefix_path, const std::string &prefix_name)
virtual void log ()
Protected Attributes
Eigen::MatrixXd H_
Eigen::MatrixXd R_
Detailed Description
Definition at line 13 of file LTIMeasurementModel.h.
Constructor & Destructor Documentation
LTIMeasurementModel()
LTIMeasurementModel::LTIMeasurementModel (const Eigen::Ref< const Eigen::MatrixXd > & measurement_matrix, const Eigen::Ref< const Eigen::MatrixXd > & noise_covariance_matrix)
Definition at line 9 of file LTIMeasurementModel.cpp.
References H_, and R_.
 LTIMeasurementModel()
virtual bfl::LTIMeasurementModel::~LTIMeasurementModel () [inline], [virtual], [noexcept]
Definition at line 18 of file LTIMeasurementModel.h.
Member Function Documentation
disable_log()
bool Logger::disable_log () [inherited]
Definition at line 58 of file Logger.cpp.
References bfl::Logger::file_names_, bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
Referenced by bfl::Logger::~Logger().
enable_log()
bool Logger::enable_log (const std::string & prefix_path, const std::string & prefix_name) [inherited]
Definition at line 15 of file Logger.cpp.
References bfl::Logger::file_names_, bfl::Logger::log_enabled_, bfl::Logger::log_filenames(), and bfl::Logger::log_files_.
freezeMeasurements()
virtual bool bfl::MeasurementModel::freezeMeasurements () [pure virtual], [inherited]
Implemented in bfl::MeasurementModelDecorator, and bfl::SimulatedLinearSensor.
get_prefix_name()
std::string Logger::get_prefix_name () const [inherited]
Definition at line 81 of file Logger.cpp.
References bfl::Logger::prefix_name_.
get_prefix_path()
std::string Logger::get_prefix_path () const [inherited]
Definition at line 75 of file Logger.cpp.
References bfl::Logger::prefix_path_.
getMeasurementMatrix()
Eigen::MatrixXd LTIMeasurementModel::getMeasurementMatrix () const [override], [virtual]
Implements bfl::LinearMeasurementModel.
Definition at line 29 of file LTIMeasurementModel.cpp.
References H_.
getNoiseCovarianceMatrix()
std::pair< bool, Eigen::MatrixXd > LTIMeasurementModel::getNoiseCovarianceMatrix () const [override], [virtual]
Reimplemented from bfl::MeasurementModel.
Definition at line 23 of file LTIMeasurementModel.cpp.
References R_.
getOutputSize()
virtual std::pair<std::size_t, std::size_t> bfl::MeasurementModel::getOutputSize () const [pure virtual], [inherited]
Implemented in bfl::SimulatedLinearSensor, and bfl::MeasurementModelDecorator.
Referenced by bfl::UKFCorrection::correctStep(), bfl::SimulatedLinearSensor::SimulatedLinearSensor(), and bfl::sigma_point::unscented_transform().
innovation()
std::pair< bool, bfl::Data > LinearMeasurementModel::innovation (const bfl::Data & predicted_measurements, const bfl::Data & measurements) const [override], [virtual], [inherited]
Implements bfl::MeasurementModel.
Definition at line 16 of file LinearMeasurementModel.cpp.
References bfl::any::any_cast().
log()
void Logger::log () [protected], [virtual], [inherited]
Reimplemented in bfl::SIS, bfl::SimulatedStateModel, and bfl::SimulatedLinearSensor.
Definition at line 99 of file Logger.cpp.
Referenced by bfl::GaussianFilter::filteringStep().
log_filenames()
std::vector< std::string > Logger::log_filenames (const std::string & prefix_path, const std::string & prefix_name) [protected], [virtual], [inherited]
Reimplemented in bfl::LinearModel, bfl::SimulatedStateModel, and bfl::SIS.
Definition at line 87 of file Logger.cpp.
Referenced by bfl::Logger::enable_log().
logger() [1/4]
template<typename DatumType >
void bfl::Logger::logger (DatumType datum) [inline], [inherited]
Definition at line 28 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
Referenced by bfl::SimulatedLinearSensor::log().
logger() [2/4]
template<typename... DataType>
void bfl::Logger::logger (DataType... data) [inline], [inherited]
Definition at line 35 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::logger_helper().
logger() [3/4]
template<typename DatumType >
void bfl::Logger::logger (DatumType datum) const [inline], [inherited]
Definition at line 42 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
logger() [4/4]
template<typename... DataType>
void bfl::Logger::logger (DataType... data) const [inline], [inherited]
Definition at line 49 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::logger_helper().
measure()
virtual std::pair<bool, bfl::Data> bfl::MeasurementModel::measure () const [pure virtual], [inherited]
Implemented in bfl::SimulatedLinearSensor, and bfl::MeasurementModelDecorator.
Referenced by bfl::UKFCorrection::correctStep(), and bfl::GaussianLikelihood::likelihood().
predictedMeasure()
std::pair< bool, bfl::Data > LinearMeasurementModel::predictedMeasure (const Eigen::Ref< const Eigen::MatrixXd > & cur_states) const [override], [virtual], [inherited]
Implements bfl::MeasurementModel.
Definition at line 9 of file LinearMeasurementModel.cpp.
setProperty()
bool MeasurementModel::setProperty (const std::string & property) [virtual], [inherited]
Reimplemented in bfl::MeasurementModelDecorator.
Definition at line 19 of file MeasurementModel.cpp.
Member Data Documentation
H_
Eigen::MatrixXd bfl::LTIMeasurementModel::H_ [protected]
Definition at line 26 of file LTIMeasurementModel.h.
Referenced by getMeasurementMatrix(), and LTIMeasurementModel().
R_
Eigen::MatrixXd bfl::LTIMeasurementModel::R_ [protected]
Definition at line 29 of file LTIMeasurementModel.h.
Referenced by getNoiseCovarianceMatrix(), and LTIMeasurementModel().
The documentation for this class was generated from the following files:
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/include/BayesFilters/LTIMeasurementModel.h
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/src/LTIMeasurementModel.cpp