bfl::SimulatedLinearSensor Class Reference
#include <SimulatedLinearSensor.h>
Public Member Functions
SimulatedLinearSensor (std::unique_ptr< bfl::SimulatedStateModel > simulated_state_model, const double sigma_x, const double sigma_y, const unsigned int seed)
SimulatedLinearSensor (std::unique_ptr< bfl::SimulatedStateModel > simulated_state_model, const double sigma_x, const double sigma_y)
SimulatedLinearSensor (std::unique_ptr< bfl::SimulatedStateModel > simulated_state_model)
virtual ~SimulatedLinearSensor () noexcept
bool freezeMeasurements () override
std::pair< bool, bfl::Data > measure () const override
std::pair< std::size_t, std::size_t > getOutputSize () const override
std::pair< bool, Eigen::MatrixXd > getNoiseCovarianceMatrix () const override
Eigen::MatrixXd getMeasurementMatrix () const override
virtual std::pair< bool, bfl::Data > predictedMeasure (const Eigen::Ref< const Eigen::MatrixXd > &cur_states) const override
virtual std::pair< bool, bfl::Data > innovation (const bfl::Data &predicted_measurements, const bfl::Data &measurements) const override
virtual bool setProperty (const std::string &property)
bool enable_log (const std::string &prefix_path, const std::string &prefix_name)
bool disable_log ()
std::string get_prefix_path () const
std::string get_prefix_name () const
template<typename DatumType >
void logger (DatumType datum)
template<typename... DataType>
void logger (DataType... data)
template<typename DatumType >
void logger (DatumType datum) const
template<typename... DataType>
void logger (DataType... data) const
Protected Member Functions
void log () override
std::pair< bool, Eigen::MatrixXd > getNoiseSample (const int num) const
std::vector< std::string > log_filenames (const std::string &prefix_path, const std::string &prefix_name) override
Protected Attributes
std::unique_ptr< bfl::SimulatedStateModel > simulated_state_model_
Eigen::MatrixXd measurement_
std::size_t dim_linear_
std::size_t dim_circular_
double T_
The Sampling interval in [time].
double sigma_x_
x-axis measurement noise std deviation in [length].
double sigma_y_
y-axis measurement noise std deviation in [length].
Eigen::MatrixXd H_
Measurement matrix.
Eigen::Matrix2d R_
Convariance matrix of the additive white noise of the measurements.
Eigen::Matrix2d sqrt_R_
Square root matrix of R_.
std::function< double()> gauss_rnd_sample_
Random number generator function from a Normal distribution.
Detailed Description
Definition at line 14 of file SimulatedLinearSensor.h.
Constructor & Destructor Documentation
SimulatedLinearSensor() [1/3]
SimulatedLinearSensor::SimulatedLinearSensor (std::unique_ptr< bfl::SimulatedStateModel > simulated_state_model, const double sigma_x, const double sigma_y, const unsigned int seed)
Definition at line 8 of file SimulatedLinearSensor.cpp.
References bfl::MeasurementModel::getOutputSize().
SimulatedLinearSensor() [2/3]
SimulatedLinearSensor::SimulatedLinearSensor (std::unique_ptr< bfl::SimulatedStateModel > simulated_state_model, const double sigma_x, const double sigma_y)
Definition at line 41 of file SimulatedLinearSensor.cpp.
SimulatedLinearSensor() [3/3]
SimulatedLinearSensor::SimulatedLinearSensor (std::unique_ptr< bfl::SimulatedStateModel > simulated_state_model)
Definition at line 50 of file SimulatedLinearSensor.cpp.
 SimulatedLinearSensor()
SimulatedLinearSensor::~SimulatedLinearSensor () [virtual], [noexcept]
Definition at line 55 of file SimulatedLinearSensor.cpp.
Member Function Documentation
disable_log()
bool Logger::disable_log () [inherited]
Definition at line 58 of file Logger.cpp.
References bfl::Logger::file_names_, bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
Referenced by bfl::Logger::~Logger().
enable_log()
bool Logger::enable_log (const std::string & prefix_path, const std::string & prefix_name) [inherited]
Definition at line 15 of file Logger.cpp.
References bfl::Logger::file_names_, bfl::Logger::log_enabled_, bfl::Logger::log_filenames(), and bfl::Logger::log_files_.
freezeMeasurements()
bool SimulatedLinearSensor::freezeMeasurements () [override], [virtual]
Implements bfl::MeasurementModel.
Definition at line 59 of file SimulatedLinearSensor.cpp.
References bfl::any::any_cast(), bfl::LinearModel::getNoiseSample(), bfl::LinearModel::H_, log(), measurement_, and simulated_state_model_.
get_prefix_name()
std::string Logger::get_prefix_name () const [inherited]
Definition at line 81 of file Logger.cpp.
References bfl::Logger::prefix_name_.
get_prefix_path()
std::string Logger::get_prefix_path () const [inherited]
Definition at line 75 of file Logger.cpp.
References bfl::Logger::prefix_path_.
getMeasurementMatrix()
Eigen::MatrixXd LinearModel::getMeasurementMatrix () const [override], [virtual], [inherited]
Implements bfl::LinearMeasurementModel.
Definition at line 151 of file LinearModel.cpp.
References bfl::LinearModel::H_.
getNoiseCovarianceMatrix()
std::pair< bool, MatrixXd > LinearModel::getNoiseCovarianceMatrix () const [override], [virtual], [inherited]
Reimplemented from bfl::MeasurementModel.
Definition at line 145 of file LinearModel.cpp.
References bfl::LinearModel::R_.
getNoiseSample()
std::pair< bool, MatrixXd > LinearModel::getNoiseSample (const int num) const [protected], [inherited]
Definition at line 133 of file LinearModel.cpp.
References bfl::LinearModel::gauss_rnd_sample_, and bfl::LinearModel::sqrt_R_.
Referenced by freezeMeasurements().
getOutputSize()
std::pair< std::size_t, std::size_t > SimulatedLinearSensor::getOutputSize () const [override], [virtual]
Implements bfl::MeasurementModel.
Definition at line 83 of file SimulatedLinearSensor.cpp.
References dim_circular_, and dim_linear_.
innovation()
std::pair< bool, bfl::Data > LinearMeasurementModel::innovation (const bfl::Data & predicted_measurements, const bfl::Data & measurements) const [override], [virtual], [inherited]
Implements bfl::MeasurementModel.
Definition at line 16 of file LinearMeasurementModel.cpp.
References bfl::any::any_cast().
log()
void SimulatedLinearSensor::log () [override], [protected], [virtual]
Reimplemented from bfl::Logger.
Definition at line 89 of file SimulatedLinearSensor.cpp.
References bfl::Logger::logger(), and measurement_.
Referenced by freezeMeasurements().
log_filenames()
std::vector<std::string> bfl::LinearModel::log_filenames (const std::string & prefix_path, const std::string & prefix_name) [inline], [override], [protected], [virtual], [inherited]
Reimplemented from bfl::Logger.
Definition at line 87 of file LinearModel.h.
logger() [1/4]
template<typename DatumType >
void bfl::Logger::logger (DatumType datum) [inline], [inherited]
Definition at line 28 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
Referenced by log().
logger() [2/4]
template<typename... DataType>
void bfl::Logger::logger (DataType... data) [inline], [inherited]
Definition at line 35 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::logger_helper().
logger() [3/4]
template<typename DatumType >
void bfl::Logger::logger (DatumType datum) const [inline], [inherited]
Definition at line 42 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
logger() [4/4]
template<typename... DataType>
void bfl::Logger::logger (DataType... data) const [inline], [inherited]
Definition at line 49 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::logger_helper().
measure()
std::pair< bool, Data > SimulatedLinearSensor::measure () const [override], [virtual]
Implements bfl::MeasurementModel.
Definition at line 77 of file SimulatedLinearSensor.cpp.
References measurement_.
predictedMeasure()
std::pair< bool, bfl::Data > LinearMeasurementModel::predictedMeasure (const Eigen::Ref< const Eigen::MatrixXd > & cur_states) const [override], [virtual], [inherited]
Implements bfl::MeasurementModel.
Definition at line 9 of file LinearMeasurementModel.cpp.
setProperty()
bool MeasurementModel::setProperty (const std::string & property) [virtual], [inherited]
Reimplemented in bfl::MeasurementModelDecorator.
Definition at line 19 of file MeasurementModel.cpp.
Member Data Documentation
dim_circular_
std::size_t bfl::SimulatedLinearSensor::dim_circular_ [protected]
Definition at line 38 of file SimulatedLinearSensor.h.
Referenced by getOutputSize().
dim_linear_
std::size_t bfl::SimulatedLinearSensor::dim_linear_ [protected]
Definition at line 36 of file SimulatedLinearSensor.h.
Referenced by getOutputSize().
gauss_rnd_sample_
std::function<double()> bfl::LinearModel::gauss_rnd_sample_ [protected], [inherited]
Random number generator function from a Normal distribution.
A call to gauss_rnd_sample_() returns a doubleing point random number.
Definition at line 85 of file LinearModel.h.
Referenced by bfl::LinearModel::getNoiseSample().
H_
Eigen::MatrixXd bfl::LinearModel::H_ [protected], [inherited]
Measurement matrix.
Definition at line 69 of file LinearModel.h.
Referenced by freezeMeasurements(), and bfl::LinearModel::getMeasurementMatrix().
measurement_
Eigen::MatrixXd bfl::SimulatedLinearSensor::measurement_ [protected]
Definition at line 34 of file SimulatedLinearSensor.h.
Referenced by freezeMeasurements(), log(), and measure().
R_
Eigen::Matrix2d bfl::LinearModel::R_ [protected], [inherited]
Convariance matrix of the additive white noise of the measurements.
Definition at line 74 of file LinearModel.h.
Referenced by bfl::LinearModel::getNoiseCovarianceMatrix().
sigma_x_
double bfl::LinearModel::sigma_x_ [protected], [inherited]
x-axis measurement noise std deviation in [length].
Definition at line 59 of file LinearModel.h.
Referenced by bfl::LinearModel::operator=().
sigma_y_
double bfl::LinearModel::sigma_y_ [protected], [inherited]
y-axis measurement noise std deviation in [length].
Definition at line 64 of file LinearModel.h.
simulated_state_model_
std::unique_ptr<bfl::SimulatedStateModel> bfl::SimulatedLinearSensor::simulated_state_model_ [protected]
Definition at line 32 of file SimulatedLinearSensor.h.
Referenced by freezeMeasurements().
sqrt_R_
Eigen::Matrix2d bfl::LinearModel::sqrt_R_ [protected], [inherited]
Square root matrix of R_.
Definition at line 79 of file LinearModel.h.
Referenced by bfl::LinearModel::getNoiseSample().
T_
double bfl::LinearModel::T_ [protected], [inherited]
The Sampling interval in [time].
Definition at line 54 of file LinearModel.h.
The documentation for this class was generated from the following files:
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/include/BayesFilters/SimulatedLinearSensor.h
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/src/SimulatedLinearSensor.cpp