bfl::ParticleSet Class Reference
#include <ParticleSet.h>
Public Member Functions
ParticleSet (const std::size_t components, const std::size_t dim) noexcept
ParticleSet (const std::size_t components, const std::size_t dim_linear, const std::size_t dim_circular) noexcept
virtual ~ParticleSet () noexcept
ParticleSet & operator+= (const ParticleSet &rhs)
Eigen::Ref< Eigen::MatrixXd > state ()
Eigen::Ref< Eigen::MatrixXd > state (const std::size_t i)
double & state (const std::size_t i, const std::size_t j)
const Eigen::Ref< const Eigen::MatrixXd > state () const
const Eigen::Ref< const Eigen::MatrixXd > state (const std::size_t i) const
const double & state (const std::size_t i, const std::size_t j) const
Eigen::Ref< Eigen::MatrixXd > mean ()
Eigen::Ref< Eigen::VectorXd > mean (const std::size_t i)
double & mean (const std::size_t i, const std::size_t j)
const Eigen::Ref< const Eigen::MatrixXd > mean () const
const Eigen::Ref< const Eigen::VectorXd > mean (const std::size_t i) const
const double & mean (const std::size_t i, const std::size_t j) const
Eigen::Ref< Eigen::MatrixXd > covariance ()
Eigen::Ref< Eigen::MatrixXd > covariance (const std::size_t i)
double & covariance (const std::size_t i, const std::size_t j, const std::size_t k)
const Eigen::Ref< const Eigen::MatrixXd > covariance () const
const Eigen::Ref< const Eigen::MatrixXd > covariance (const std::size_t i) const
const double & covariance (const std::size_t i, const std::size_t j, const std::size_t k) const
Eigen::Ref< Eigen::VectorXd > weight ()
double & weight (const std::size_t i)
const Eigen::Ref< const Eigen::VectorXd > weight () const
const double & weight (const std::size_t i) const
bool augmentWithNoise (const Eigen::Ref< const Eigen::MatrixXd > &noise_covariance_matrix)
Public Attributes
std::size_t components
std::size_t dim
std::size_t dim_linear
std::size_t dim_circular
std::size_t dim_noise
Protected Attributes
Eigen::MatrixXd state_
Eigen::MatrixXd mean_
Eigen::MatrixXd covariance_
Eigen::VectorXd weight_
Detailed Description
Definition at line 13 of file ParticleSet.h.
Constructor & Destructor Documentation
ParticleSet() [1/2]
ParticleSet::ParticleSet (const std::size_t components, const std::size_t dim) [noexcept]
Definition at line 7 of file ParticleSet.cpp.
ParticleSet() [2/2]
ParticleSet::ParticleSet (const std::size_t components, const std::size_t dim_linear, const std::size_t dim_circular) [noexcept]
Definition at line 12 of file ParticleSet.cpp.
 ParticleSet()
ParticleSet::~ParticleSet () [virtual], [noexcept]
Definition at line 21 of file ParticleSet.cpp.
Member Function Documentation
augmentWithNoise()
bool GaussianMixture::augmentWithNoise (const Eigen::Ref< const Eigen::MatrixXd > & noise_covariance_matrix) [inherited]
Definition at line 136 of file GaussianMixture.cpp.
References bfl::GaussianMixture::components, bfl::GaussianMixture::covariance_, bfl::GaussianMixture::dim, bfl::GaussianMixture::dim_circular, bfl::GaussianMixture::dim_linear, bfl::GaussianMixture::dim_noise, and bfl::GaussianMixture::mean_.
Referenced by bfl::UKFCorrection::correctStep(), and bfl::UKFPrediction::predictStep().
covariance() [1/6]
Ref< MatrixXd > GaussianMixture::covariance () [inherited]
Definition at line 76 of file GaussianMixture.cpp.
References bfl::GaussianMixture::covariance_.
Referenced by bfl::KFCorrection::correctStep(), bfl::UKFCorrection::correctStep(), bfl::GPFCorrection::correctStep(), bfl::SUKFCorrection::correctStep(), bfl::KFPrediction::predictStep(), bfl::Resampling::resample(), bfl::ResamplingWithPrior::resample(), bfl::sigma_point::sigma_point(), and bfl::sigma_point::unscented_transform().
covariance() [2/6]
Ref< MatrixXd > GaussianMixture::covariance (const std::size_t i) [inherited]
Definition at line 82 of file GaussianMixture.cpp.
References bfl::GaussianMixture::covariance_, and bfl::GaussianMixture::dim.
covariance() [3/6]
double & GaussianMixture::covariance (const std::size_t i, const std::size_t j, const std::size_t k) [inherited]
Definition at line 88 of file GaussianMixture.cpp.
References bfl::GaussianMixture::covariance_, and bfl::GaussianMixture::dim.
covariance() [4/6]
const Ref< const MatrixXd > GaussianMixture::covariance () const [inherited]
Definition at line 94 of file GaussianMixture.cpp.
References bfl::GaussianMixture::covariance_.
covariance() [5/6]
const Ref< const MatrixXd > GaussianMixture::covariance (const std::size_t i) const [inherited]
Definition at line 100 of file GaussianMixture.cpp.
References bfl::GaussianMixture::covariance_, and bfl::GaussianMixture::dim.
covariance() [6/6]
const double & GaussianMixture::covariance (const std::size_t i, const std::size_t j, const std::size_t k) const [inherited]
Definition at line 106 of file GaussianMixture.cpp.
References bfl::GaussianMixture::covariance_, and bfl::GaussianMixture::dim.
mean() [1/6]
Ref< MatrixXd > GaussianMixture::mean () [inherited]
Definition at line 40 of file GaussianMixture.cpp.
References bfl::GaussianMixture::mean_.
Referenced by bfl::KFCorrection::correctStep(), bfl::UKFCorrection::correctStep(), bfl::GPFCorrection::correctStep(), bfl::SUKFCorrection::correctStep(), bfl::KFPrediction::predictStep(), bfl::Resampling::resample(), bfl::ResamplingWithPrior::resample(), bfl::sigma_point::sigma_point(), and bfl::sigma_point::unscented_transform().
mean() [2/6]
Ref< VectorXd > GaussianMixture::mean (const std::size_t i) [inherited]
Definition at line 46 of file GaussianMixture.cpp.
References bfl::GaussianMixture::mean_.
mean() [3/6]
double & GaussianMixture::mean (const std::size_t i, const std::size_t j) [inherited]
Definition at line 52 of file GaussianMixture.cpp.
References bfl::GaussianMixture::mean_.
mean() [4/6]
const Ref< const MatrixXd > GaussianMixture::mean () const [inherited]
Definition at line 58 of file GaussianMixture.cpp.
References bfl::GaussianMixture::mean_.
mean() [5/6]
const Ref< const VectorXd > GaussianMixture::mean (const std::size_t i) const [inherited]
Definition at line 64 of file GaussianMixture.cpp.
References bfl::GaussianMixture::mean_.
mean() [6/6]
const double & GaussianMixture::mean (const std::size_t i, const std::size_t j) const [inherited]
Definition at line 70 of file GaussianMixture.cpp.
References bfl::GaussianMixture::mean_.
operator+=()
ParticleSet & ParticleSet::operator+= (const ParticleSet & rhs)
Definition at line 24 of file ParticleSet.cpp.
References bfl::GaussianMixture::components, bfl::GaussianMixture::covariance_, bfl::GaussianMixture::mean_, state_, and bfl::GaussianMixture::weight_.
state() [1/6]
Ref< MatrixXd > ParticleSet::state ()
Definition at line 53 of file ParticleSet.cpp.
Referenced by bfl::BoostrapCorrection::correctStep(), bfl::GPFCorrection::correctStep(), bfl::InitSurveillanceAreaGrid::initialize(), bfl::DrawParticles::predictStep(), bfl::GPFPrediction::predictStep(), bfl::ResamplingWithPrior::resample(), and bfl::Resampling::resample().
state() [2/6]
Ref< MatrixXd > ParticleSet::state (const std::size_t i)
Definition at line 59 of file ParticleSet.cpp.
state() [3/6]
double & ParticleSet::state (const std::size_t i, const std::size_t j)
Definition at line 65 of file ParticleSet.cpp.
state() [4/6]
const Ref< const MatrixXd > ParticleSet::state () const
Definition at line 71 of file ParticleSet.cpp.
state() [5/6]
const Ref< const MatrixXd > ParticleSet::state (const std::size_t i) const
Definition at line 77 of file ParticleSet.cpp.
state() [6/6]
const double & ParticleSet::state (const std::size_t i, const std::size_t j) const
Definition at line 83 of file ParticleSet.cpp.
weight() [1/4]
Ref< VectorXd > GaussianMixture::weight () [inherited]
Definition at line 112 of file GaussianMixture.cpp.
References bfl::GaussianMixture::weight_.
Referenced by bfl::BoostrapCorrection::correctStep(), bfl::GPFCorrection::correctStep(), bfl::InitSurveillanceAreaGrid::initialize(), bfl::DrawParticles::predictStep(), bfl::GPFPrediction::predictStep(), bfl::ResamplingWithPrior::resample(), and bfl::Resampling::resample().
weight() [2/4]
double & GaussianMixture::weight (const std::size_t i) [inherited]
Definition at line 118 of file GaussianMixture.cpp.
References bfl::GaussianMixture::weight_.
weight() [3/4]
const Ref< const VectorXd > GaussianMixture::weight () const [inherited]
Definition at line 124 of file GaussianMixture.cpp.
References bfl::GaussianMixture::weight_.
weight() [4/4]
const double & GaussianMixture::weight (const std::size_t i) const [inherited]
Definition at line 130 of file GaussianMixture.cpp.
References bfl::GaussianMixture::weight_.
Member Data Documentation
components
std::size_t bfl::GaussianMixture::components [inherited]
Definition at line 58 of file GaussianMixture.h.
Referenced by bfl::GaussianMixture::augmentWithNoise(), bfl::KFCorrection::correctStep(), bfl::UKFCorrection::correctStep(), bfl::GPFCorrection::correctStep(), bfl::SUKFCorrection::correctStep(), operator+=(), bfl::KFPrediction::predictStep(), bfl::sigma_point::sigma_point(), and bfl::sigma_point::unscented_transform().
covariance_
Eigen::MatrixXd bfl::GaussianMixture::covariance_ [protected], [inherited]
Definition at line 71 of file GaussianMixture.h.
Referenced by bfl::GaussianMixture::augmentWithNoise(), bfl::GaussianMixture::covariance(), bfl::Gaussian::covariance(), and operator+=().
dim
std::size_t bfl::GaussianMixture::dim [inherited]
Definition at line 60 of file GaussianMixture.h.
Referenced by bfl::GaussianMixture::augmentWithNoise(), bfl::SUKFCorrection::correctStep(), bfl::GaussianMixture::covariance(), bfl::sigma_point::sigma_point(), and bfl::sigma_point::unscented_transform().
dim_circular
std::size_t bfl::GaussianMixture::dim_circular [inherited]
Definition at line 64 of file GaussianMixture.h.
Referenced by bfl::GaussianMixture::augmentWithNoise(), bfl::SUKFCorrection::correctStep(), bfl::ResamplingWithPrior::resample(), bfl::sigma_point::sigma_point(), and bfl::sigma_point::unscented_transform().
dim_linear
std::size_t bfl::GaussianMixture::dim_linear [inherited]
Definition at line 62 of file GaussianMixture.h.
Referenced by bfl::GaussianMixture::augmentWithNoise(), bfl::SUKFCorrection::correctStep(), bfl::ResamplingWithPrior::resample(), bfl::sigma_point::sigma_point(), and bfl::sigma_point::unscented_transform().
dim_noise
std::size_t bfl::GaussianMixture::dim_noise [inherited]
Definition at line 66 of file GaussianMixture.h.
Referenced by bfl::GaussianMixture::augmentWithNoise(), and bfl::sigma_point::sigma_point().
mean_
Eigen::MatrixXd bfl::GaussianMixture::mean_ [protected], [inherited]
Definition at line 69 of file GaussianMixture.h.
Referenced by bfl::GaussianMixture::augmentWithNoise(), bfl::GaussianMixture::mean(), bfl::Gaussian::mean(), and operator+=().
state_
Eigen::MatrixXd bfl::ParticleSet::state_ [protected]
Definition at line 37 of file ParticleSet.h.
Referenced by operator+=().
weight_
Eigen::VectorXd bfl::GaussianMixture::weight_ [protected], [inherited]
Definition at line 73 of file GaussianMixture.h.
Referenced by operator+=(), bfl::Gaussian::weight(), and bfl::GaussianMixture::weight().
The documentation for this class was generated from the following files:
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/include/BayesFilters/ParticleSet.h
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/src/ParticleSet.cpp