bfl::StateModel Class Reference
#include <StateModel.h>
Public Member Functions
virtual ~StateModel () noexcept
virtual void propagate (const Eigen::Ref< const Eigen::MatrixXd > &cur_states, Eigen::Ref< Eigen::MatrixXd > prop_states)=0
virtual void motion (const Eigen::Ref< const Eigen::MatrixXd > &cur_states, Eigen::Ref< Eigen::MatrixXd > mot_states)=0
virtual Eigen::MatrixXd getJacobian ()
virtual Eigen::VectorXd getTransitionProbability (const Eigen::Ref< const Eigen::MatrixXd > &prev_states, Eigen::Ref< Eigen::MatrixXd > cur_states)
virtual Eigen::MatrixXd getNoiseCovarianceMatrix ()
virtual Eigen::MatrixXd getNoiseSample (const std::size_t num)
virtual bool setProperty (const std::string &property)=0
virtual std::pair< std::size_t, std::size_t > getOutputSize () const =0
Returns the linear and circular size of the output of the state equation.
Detailed Description
Definition at line 11 of file StateModel.h.
Constructor & Destructor Documentation
 StateModel()
virtual bfl::StateModel::~StateModel () [inline], [virtual], [noexcept]
Definition at line 14 of file StateModel.h.
Member Function Documentation
getJacobian()
Eigen::MatrixXd StateModel::getJacobian () [virtual]
Reimplemented in bfl::LTIStateModel.
Definition at line 7 of file StateModel.cpp.
getNoiseCovarianceMatrix()
Eigen::MatrixXd StateModel::getNoiseCovarianceMatrix () [virtual]
Reimplemented in bfl::WhiteNoiseAcceleration, bfl::LTIStateModel, and bfl::StateModelDecorator.
Definition at line 19 of file StateModel.cpp.
Referenced by bfl::sigma_point::unscented_transform().
getNoiseSample()
Eigen::MatrixXd StateModel::getNoiseSample (const std::size_t num) [virtual]
Reimplemented in bfl::WhiteNoiseAcceleration, and bfl::StateModelDecorator.
Definition at line 25 of file StateModel.cpp.
getOutputSize()
virtual std::pair<std::size_t, std::size_t> bfl::StateModel::getOutputSize () const [pure virtual]
Returns the linear and circular size of the output of the state equation.
Implemented in bfl::WhiteNoiseAcceleration, and bfl::StateModelDecorator.
Referenced by bfl::sigma_point::unscented_transform().
getTransitionProbability()
Eigen::VectorXd StateModel::getTransitionProbability (const Eigen::Ref< const Eigen::MatrixXd > & prev_states, Eigen::Ref< Eigen::MatrixXd > cur_states) [virtual]
Reimplemented in bfl::WhiteNoiseAcceleration.
Definition at line 13 of file StateModel.cpp.
motion()
virtual void bfl::StateModel::motion (const Eigen::Ref< const Eigen::MatrixXd > & cur_states, Eigen::Ref< Eigen::MatrixXd > mot_states) [pure virtual]
Implemented in bfl::AdditiveStateModel, and bfl::StateModelDecorator.
Referenced by bfl::sigma_point::unscented_transform().
propagate()
virtual void bfl::StateModel::propagate (const Eigen::Ref< const Eigen::MatrixXd > & cur_states, Eigen::Ref< Eigen::MatrixXd > prop_states) [pure virtual]
Implemented in bfl::LTIStateModel, bfl::LinearStateModel, and bfl::StateModelDecorator.
Referenced by bfl::sigma_point::unscented_transform().
setProperty()
virtual bool bfl::StateModel::setProperty (const std::string & property) [pure virtual]
Implemented in bfl::WhiteNoiseAcceleration, bfl::LTIStateModel, and bfl::StateModelDecorator.
The documentation for this class was generated from the following files:
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/include/BayesFilters/StateModel.h
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/src/StateModel.cpp