bfl::GaussianLikelihood Class Reference
#include <GaussianLikelihood.h>
Public Member Functions
GaussianLikelihood () noexcept
GaussianLikelihood (const double scale_factor) noexcept
virtual ~GaussianLikelihood () noexcept
Protected Member Functions
std::pair< bool, Eigen::VectorXd > likelihood (const MeasurementModel &measurement_model, const Eigen::Ref< const Eigen::MatrixXd > &pred_states) override
Protected Attributes
double scale_factor_
Detailed Description
Definition at line 11 of file GaussianLikelihood.h.
Constructor & Destructor Documentation
GaussianLikelihood() [1/2]
GaussianLikelihood::GaussianLikelihood () [noexcept]
Definition at line 7 of file GaussianLikelihood.cpp.
GaussianLikelihood() [2/2]
GaussianLikelihood::GaussianLikelihood (const double scale_factor) [noexcept]
Definition at line 11 of file GaussianLikelihood.cpp.
 GaussianLikelihood()
virtual bfl::GaussianLikelihood::~GaussianLikelihood () [inline], [virtual], [noexcept]
Definition at line 18 of file GaussianLikelihood.h.
Member Function Documentation
likelihood()
std::pair< bool, VectorXd > GaussianLikelihood::likelihood (const MeasurementModel & measurement_model, const Eigen::Ref< const Eigen::MatrixXd > & pred_states) [override], [protected], [virtual]
Implements bfl::LikelihoodModel.
Definition at line 16 of file GaussianLikelihood.cpp.
References bfl::any::any_cast(), bfl::MeasurementModel::getNoiseCovarianceMatrix(), bfl::MeasurementModel::innovation(), bfl::MeasurementModel::measure(), and bfl::MeasurementModel::predictedMeasure().
Member Data Documentation
scale_factor_
double bfl::GaussianLikelihood::scale_factor_ [protected]
Definition at line 23 of file GaussianLikelihood.h.
The documentation for this class was generated from the following files:
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/include/BayesFilters/GaussianLikelihood.h
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/src/GaussianLikelihood.cpp