bfl::LinearModel Class Reference
#include <LinearModel.h>
Public Member Functions
LinearModel (const double sigma_x, const double sigma_y, const unsigned int seed) noexcept
LinearModel (const double sigma_x, const double sigma_y) noexcept
LinearModel () noexcept
LinearModel (const LinearModel &lin_sense)
LinearModel (LinearModel &&lin_sense) noexcept
virtual ~LinearModel () noexcept
LinearModel & operator= (const LinearModel &lin_sense) noexcept
LinearModel & operator= (LinearModel &&lin_sense) noexcept
std::pair< bool, Eigen::MatrixXd > getNoiseCovarianceMatrix () const override
Eigen::MatrixXd getMeasurementMatrix () const override
virtual std::pair< bool, bfl::Data > predictedMeasure (const Eigen::Ref< const Eigen::MatrixXd > &cur_states) const override
virtual std::pair< bool, bfl::Data > innovation (const bfl::Data &predicted_measurements, const bfl::Data &measurements) const override
virtual std::pair< bool, bfl::Data > measure () const =0
virtual bool setProperty (const std::string &property)
virtual bool freezeMeasurements ()=0
virtual std::pair< std::size_t, std::size_t > getOutputSize () const =0
bool enable_log (const std::string &prefix_path, const std::string &prefix_name)
bool disable_log ()
std::string get_prefix_path () const
std::string get_prefix_name () const
template<typename DatumType >
void logger (DatumType datum)
template<typename... DataType>
void logger (DataType... data)
template<typename DatumType >
void logger (DatumType datum) const
template<typename... DataType>
void logger (DataType... data) const
Protected Member Functions
std::pair< bool, Eigen::MatrixXd > getNoiseSample (const int num) const
std::vector< std::string > log_filenames (const std::string &prefix_path, const std::string &prefix_name) override
virtual void log ()
Protected Attributes
double T_
The Sampling interval in [time].
double sigma_x_
x-axis measurement noise std deviation in [length].
double sigma_y_
y-axis measurement noise std deviation in [length].
Eigen::MatrixXd H_
Measurement matrix.
Eigen::Matrix2d R_
Convariance matrix of the additive white noise of the measurements.
Eigen::Matrix2d sqrt_R_
Square root matrix of R_.
std::function< double()> gauss_rnd_sample_
Random number generator function from a Normal distribution.
Private Attributes
std::mt19937_64 generator_
std::normal_distribution< double > distribution_
bool log_enabled_ = false
std::ofstream log_file_measurements_
Detailed Description
Definition at line 16 of file LinearModel.h.
Constructor & Destructor Documentation
LinearModel() [1/5]
LinearModel::LinearModel (const double sigma_x, const double sigma_y, const unsigned int seed) [noexcept]
Definition at line 12 of file LinearModel.cpp.
LinearModel() [2/5]
LinearModel::LinearModel (const double sigma_x, const double sigma_y) [noexcept]
Definition at line 35 of file LinearModel.cpp.
LinearModel() [3/5]
LinearModel::LinearModel () [noexcept]
Definition at line 39 of file LinearModel.cpp.
LinearModel() [4/5]
LinearModel::LinearModel (const LinearModel & lin_sense)
Definition at line 47 of file LinearModel.cpp.
References log_enabled_.
LinearModel() [5/5]
LinearModel::LinearModel (LinearModel && lin_sense) [noexcept]
Definition at line 63 of file LinearModel.cpp.
 LinearModel()
LinearModel::~LinearModel () [virtual], [noexcept]
Definition at line 43 of file LinearModel.cpp.
Member Function Documentation
disable_log()
bool Logger::disable_log () [inherited]
Definition at line 58 of file Logger.cpp.
References bfl::Logger::file_names_, bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
Referenced by bfl::Logger::~Logger().
enable_log()
bool Logger::enable_log (const std::string & prefix_path, const std::string & prefix_name) [inherited]
Definition at line 15 of file Logger.cpp.
References bfl::Logger::file_names_, bfl::Logger::log_enabled_, bfl::Logger::log_filenames(), and bfl::Logger::log_files_.
freezeMeasurements()
virtual bool bfl::MeasurementModel::freezeMeasurements () [pure virtual], [inherited]
Implemented in bfl::MeasurementModelDecorator, and bfl::SimulatedLinearSensor.
get_prefix_name()
std::string Logger::get_prefix_name () const [inherited]
Definition at line 81 of file Logger.cpp.
References bfl::Logger::prefix_name_.
get_prefix_path()
std::string Logger::get_prefix_path () const [inherited]
Definition at line 75 of file Logger.cpp.
References bfl::Logger::prefix_path_.
getMeasurementMatrix()
Eigen::MatrixXd LinearModel::getMeasurementMatrix () const [override], [virtual]
Implements bfl::LinearMeasurementModel.
Definition at line 151 of file LinearModel.cpp.
References H_.
getNoiseCovarianceMatrix()
std::pair< bool, MatrixXd > LinearModel::getNoiseCovarianceMatrix () const [override], [virtual]
Reimplemented from bfl::MeasurementModel.
Definition at line 145 of file LinearModel.cpp.
References R_.
getNoiseSample()
std::pair< bool, MatrixXd > LinearModel::getNoiseSample (const int num) const [protected]
Definition at line 133 of file LinearModel.cpp.
References gauss_rnd_sample_, and sqrt_R_.
Referenced by bfl::SimulatedLinearSensor::freezeMeasurements().
getOutputSize()
virtual std::pair<std::size_t, std::size_t> bfl::MeasurementModel::getOutputSize () const [pure virtual], [inherited]
Implemented in bfl::SimulatedLinearSensor, and bfl::MeasurementModelDecorator.
Referenced by bfl::UKFCorrection::correctStep(), bfl::SimulatedLinearSensor::SimulatedLinearSensor(), and bfl::sigma_point::unscented_transform().
innovation()
std::pair< bool, bfl::Data > LinearMeasurementModel::innovation (const bfl::Data & predicted_measurements, const bfl::Data & measurements) const [override], [virtual], [inherited]
Implements bfl::MeasurementModel.
Definition at line 16 of file LinearMeasurementModel.cpp.
References bfl::any::any_cast().
log()
void Logger::log () [protected], [virtual], [inherited]
Reimplemented in bfl::SIS, bfl::SimulatedStateModel, and bfl::SimulatedLinearSensor.
Definition at line 99 of file Logger.cpp.
Referenced by bfl::GaussianFilter::filteringStep().
log_filenames()
std::vector<std::string> bfl::LinearModel::log_filenames (const std::string & prefix_path, const std::string & prefix_name) [inline], [override], [protected], [virtual]
Reimplemented from bfl::Logger.
Definition at line 87 of file LinearModel.h.
logger() [1/4]
template<typename DatumType >
void bfl::Logger::logger (DatumType datum) [inline], [inherited]
Definition at line 28 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
Referenced by bfl::SimulatedLinearSensor::log().
logger() [2/4]
template<typename... DataType>
void bfl::Logger::logger (DataType... data) [inline], [inherited]
Definition at line 35 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::logger_helper().
logger() [3/4]
template<typename DatumType >
void bfl::Logger::logger (DatumType datum) const [inline], [inherited]
Definition at line 42 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
logger() [4/4]
template<typename... DataType>
void bfl::Logger::logger (DataType... data) const [inline], [inherited]
Definition at line 49 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::logger_helper().
measure()
virtual std::pair<bool, bfl::Data> bfl::MeasurementModel::measure () const [pure virtual], [inherited]
Implemented in bfl::SimulatedLinearSensor, and bfl::MeasurementModelDecorator.
Referenced by bfl::UKFCorrection::correctStep(), and bfl::GaussianLikelihood::likelihood().
operator=() [1/2]
LinearModel & LinearModel::operator= (const LinearModel & lin_sense) [noexcept]
Definition at line 85 of file LinearModel.cpp.
References sigma_x_.
operator=() [2/2]
LinearModel & LinearModel::operator= (LinearModel && lin_sense) [noexcept]
Definition at line 107 of file LinearModel.cpp.
References sigma_x_.
predictedMeasure()
std::pair< bool, bfl::Data > LinearMeasurementModel::predictedMeasure (const Eigen::Ref< const Eigen::MatrixXd > & cur_states) const [override], [virtual], [inherited]
Implements bfl::MeasurementModel.
Definition at line 9 of file LinearMeasurementModel.cpp.
setProperty()
bool MeasurementModel::setProperty (const std::string & property) [virtual], [inherited]
Reimplemented in bfl::MeasurementModelDecorator.
Definition at line 19 of file MeasurementModel.cpp.
Member Data Documentation
distribution_
std::normal_distribution<double> bfl::LinearModel::distribution_ [private]
Definition at line 42 of file LinearModel.h.
gauss_rnd_sample_
std::function<double()> bfl::LinearModel::gauss_rnd_sample_ [protected]
Random number generator function from a Normal distribution.
A call to gauss_rnd_sample_() returns a doubleing point random number.
Definition at line 85 of file LinearModel.h.
Referenced by getNoiseSample().
generator_
std::mt19937_64 bfl::LinearModel::generator_ [private]
Definition at line 40 of file LinearModel.h.
H_
Eigen::MatrixXd bfl::LinearModel::H_ [protected]
Measurement matrix.
Definition at line 69 of file LinearModel.h.
Referenced by bfl::SimulatedLinearSensor::freezeMeasurements(), and getMeasurementMatrix().
log_enabled_
bool bfl::LinearModel::log_enabled_ = false [private]
Definition at line 44 of file LinearModel.h.
Referenced by LinearModel().
log_file_measurements_
std::ofstream bfl::LinearModel::log_file_measurements_ [mutable], [private]
Definition at line 46 of file LinearModel.h.
R_
Eigen::Matrix2d bfl::LinearModel::R_ [protected]
Convariance matrix of the additive white noise of the measurements.
Definition at line 74 of file LinearModel.h.
Referenced by getNoiseCovarianceMatrix().
sigma_x_
double bfl::LinearModel::sigma_x_ [protected]
x-axis measurement noise std deviation in [length].
Definition at line 59 of file LinearModel.h.
Referenced by operator=().
sigma_y_
double bfl::LinearModel::sigma_y_ [protected]
y-axis measurement noise std deviation in [length].
Definition at line 64 of file LinearModel.h.
sqrt_R_
Eigen::Matrix2d bfl::LinearModel::sqrt_R_ [protected]
Square root matrix of R_.
Definition at line 79 of file LinearModel.h.
Referenced by getNoiseSample().
T_
double bfl::LinearModel::T_ [protected]
The Sampling interval in [time].
Definition at line 54 of file LinearModel.h.
The documentation for this class was generated from the following files:
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/include/BayesFilters/LinearModel.h
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/src/LinearModel.cpp