bfl::SIS Class Reference
#include <SIS.h>
Public Member Functions
SIS (unsigned int num_particle, std::size_t state_size_linear, std::unique_ptr< ParticleSetInitialization > initialization, std::unique_ptr< PFPrediction > prediction, std::unique_ptr< PFCorrection > correction, std::unique_ptr< Resampling > resampling) noexcept
SIS (unsigned int num_particle, std::size_t state_size_linear, std::size_t state_size_circular, std::unique_ptr< ParticleSetInitialization > initialization, std::unique_ptr< PFPrediction > prediction, std::unique_ptr< PFCorrection > correction, std::unique_ptr< Resampling > resampling) noexcept
SIS (SIS &&sir_pf) noexcept
virtual ~SIS () noexcept
SIS & operator= (SIS &&sir_pf) noexcept
bool initialization () override
bool runCondition () override
virtual bool skip (const std::string &what_step, const bool status) override
bool boot ()
void run ()
bool wait ()
void reset ()
void reboot ()
bool teardown ()
unsigned int getFilteringStep ()
bool isRunning ()
bool enable_log (const std::string &prefix_path, const std::string &prefix_name)
bool disable_log ()
std::string get_prefix_path () const
std::string get_prefix_name () const
template<typename DatumType >
void logger (DatumType datum)
template<typename... DataType>
void logger (DataType... data)
template<typename DatumType >
void logger (DatumType datum) const
template<typename... DataType>
void logger (DataType... data) const
Protected Member Functions
void filteringStep () override
std::vector< std::string > log_filenames (const std::string &prefix_path, const std::string &prefix_name) override
void log () override
Protected Attributes
unsigned int num_particle_
std::size_t state_size_
ParticleSet pred_particle_
ParticleSet cor_particle_
std::unique_ptr< ParticleSetInitialization > initialization_
std::unique_ptr< PFPrediction > prediction_
std::unique_ptr< PFCorrection > correction_
std::unique_ptr< Resampling > resampling_
Detailed Description
Definition at line 20 of file SIS.h.
Constructor & Destructor Documentation
SIS() [1/3]
SIS::SIS (unsigned int num_particle, std::size_t state_size_linear, std::unique_ptr< ParticleSetInitialization > initialization, std::unique_ptr< PFPrediction > prediction, std::unique_ptr< PFCorrection > correction, std::unique_ptr< Resampling > resampling) [noexcept]
Definition at line 33 of file SIS.cpp.
SIS() [2/3]
SIS::SIS (unsigned int num_particle, std::size_t state_size_linear, std::size_t state_size_circular, std::unique_ptr< ParticleSetInitialization > initialization, std::unique_ptr< PFPrediction > prediction, std::unique_ptr< PFCorrection > correction, std::unique_ptr< Resampling > resampling) [noexcept]
Definition at line 15 of file SIS.cpp.
SIS() [3/3]
SIS::SIS (SIS && sir_pf) [noexcept]
Definition at line 49 of file SIS.cpp.
 SIS()
SIS::~SIS () [virtual], [noexcept]
Definition at line 45 of file SIS.cpp.
Member Function Documentation
boot()
bool FilteringAlgorithm::boot () [inherited]
Definition at line 8 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::filtering_thread_, and bfl::FilteringAlgorithm::filteringRecursion().
disable_log()
bool Logger::disable_log () [inherited]
Definition at line 58 of file Logger.cpp.
References bfl::Logger::file_names_, bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
Referenced by bfl::Logger::~Logger().
enable_log()
bool Logger::enable_log (const std::string & prefix_path, const std::string & prefix_name) [inherited]
Definition at line 15 of file Logger.cpp.
References bfl::Logger::file_names_, bfl::Logger::log_enabled_, bfl::Logger::log_filenames(), and bfl::Logger::log_files_.
filteringStep()
void SIS::filteringStep () [override], [protected], [virtual]
Implements bfl::FilteringAlgorithm.
Definition at line 80 of file SIS.cpp.
References bfl::utils::log_sum_exp().
get_prefix_name()
std::string Logger::get_prefix_name () const [inherited]
Definition at line 81 of file Logger.cpp.
References bfl::Logger::prefix_name_.
get_prefix_path()
std::string Logger::get_prefix_path () const [inherited]
Definition at line 75 of file Logger.cpp.
References bfl::Logger::prefix_path_.
getFilteringStep()
unsigned int FilteringAlgorithm::getFilteringStep () [inherited]
Definition at line 83 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::filtering_step_.
initialization()
bool SIS::initialization () [override], [virtual]
Implements bfl::FilteringAlgorithm.
Definition at line 74 of file SIS.cpp.
isRunning()
bool FilteringAlgorithm::isRunning () [inherited]
Definition at line 89 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::run_.
log()
void SIS::log () [override], [protected], [virtual]
Reimplemented from bfl::Logger.
Definition at line 110 of file SIS.cpp.
log_filenames()
std::vector<std::string> bfl::SIS::log_filenames (const std::string & prefix_path, const std::string & prefix_name) [inline], [override], [protected], [virtual]
Reimplemented from bfl::Logger.
Definition at line 48 of file SIS.h.
logger() [1/4]
template<typename DatumType >
void bfl::Logger::logger (DatumType datum) [inline], [inherited]
Definition at line 28 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
Referenced by bfl::SimulatedLinearSensor::log().
logger() [2/4]
template<typename... DataType>
void bfl::Logger::logger (DataType... data) [inline], [inherited]
Definition at line 35 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::logger_helper().
logger() [3/4]
template<typename DatumType >
void bfl::Logger::logger (DatumType datum) const [inline], [inherited]
Definition at line 42 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
logger() [4/4]
template<typename... DataType>
void bfl::Logger::logger (DataType... data) const [inline], [inherited]
Definition at line 49 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::logger_helper().
operator=()
SIS & SIS::operator= (SIS && sir_pf) [noexcept]
Definition at line 58 of file SIS.cpp.
References bfl::ParticleFilter::operator=().
reboot()
void FilteringAlgorithm::reboot () [inherited]
Definition at line 66 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::cv_run_, bfl::FilteringAlgorithm::mtx_run_, bfl::FilteringAlgorithm::reset_, and bfl::FilteringAlgorithm::run_.
reset()
void FilteringAlgorithm::reset () [inherited]
Definition at line 60 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::reset_.
run()
void FilteringAlgorithm::run () [inherited]
Definition at line 26 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::cv_run_, bfl::FilteringAlgorithm::mtx_run_, and bfl::FilteringAlgorithm::run_.
runCondition()
bool SIS::runCondition () [override], [virtual]
Implements bfl::FilteringAlgorithm.
Definition at line 104 of file SIS.cpp.
skip()
bool ParticleFilter::skip (const std::string & what_step, const bool status) [override], [virtual], [inherited]
Implements bfl::FilteringAlgorithm.
Definition at line 44 of file ParticleFilter.cpp.
References bfl::ParticleFilter::correction_, and bfl::ParticleFilter::prediction_.
teardown()
bool FilteringAlgorithm::teardown () [inherited]
Definition at line 75 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::teardown_.
wait()
bool FilteringAlgorithm::wait () [inherited]
Definition at line 34 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::filtering_thread_.
Member Data Documentation
cor_particle_
ParticleSet bfl::SIS::cor_particle_ [protected]
Definition at line 44 of file SIS.h.
correction_
std::unique_ptr<PFCorrection> bfl::ParticleFilter::correction_ [protected], [inherited]
Definition at line 35 of file ParticleFilter.h.
Referenced by bfl::ParticleFilter::skip().
initialization_
std::unique_ptr<ParticleSetInitialization> bfl::ParticleFilter::initialization_ [protected], [inherited]
Definition at line 31 of file ParticleFilter.h.
num_particle_
unsigned int bfl::SIS::num_particle_ [protected]
Definition at line 38 of file SIS.h.
pred_particle_
ParticleSet bfl::SIS::pred_particle_ [protected]
Definition at line 42 of file SIS.h.
prediction_
std::unique_ptr<PFPrediction> bfl::ParticleFilter::prediction_ [protected], [inherited]
Definition at line 33 of file ParticleFilter.h.
Referenced by bfl::ParticleFilter::skip().
resampling_
std::unique_ptr<Resampling> bfl::ParticleFilter::resampling_ [protected], [inherited]
Definition at line 37 of file ParticleFilter.h.
state_size_
std::size_t bfl::SIS::state_size_ [protected]
Definition at line 40 of file SIS.h.
The documentation for this class was generated from the following files:
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/include/BayesFilters/SIS.h
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/src/SIS.cpp