bfl::GaussianFilter Class Reference
#include <GaussianFilter.h>
Public Member Functions
GaussianFilter (Gaussian &initial_state, std::unique_ptr< GaussianPrediction > prediction, std::unique_ptr< GaussianCorrection > correction) noexcept
GaussianFilter (GaussianFilter &&kf) noexcept
GaussianFilter & operator= (GaussianFilter &&gf) noexcept
virtual ~GaussianFilter () noexcept
bool initialization () override
void filteringStep () override
bool runCondition () override
bool skip (const std::string &what_step, const bool status) override
bool boot ()
void run ()
bool wait ()
void reset ()
void reboot ()
bool teardown ()
unsigned int getFilteringStep ()
bool isRunning ()
bool enable_log (const std::string &prefix_path, const std::string &prefix_name)
bool disable_log ()
std::string get_prefix_path () const
std::string get_prefix_name () const
template<typename DatumType >
void logger (DatumType datum)
template<typename... DataType>
void logger (DataType... data)
template<typename DatumType >
void logger (DatumType datum) const
template<typename... DataType>
void logger (DataType... data) const
Protected Member Functions
virtual std::vector< std::string > log_filenames (const std::string &prefix_path, const std::string &prefix_name)
virtual void log ()
Protected Attributes
Gaussian predicted_state_
Gaussian corrected_state_
std::unique_ptr< GaussianPrediction > prediction_
std::unique_ptr< GaussianCorrection > correction_
Detailed Description
Definition at line 14 of file GaussianFilter.h.
Constructor & Destructor Documentation
GaussianFilter() [1/2]
GaussianFilter::GaussianFilter (Gaussian & initial_state, std::unique_ptr< GaussianPrediction > prediction, std::unique_ptr< GaussianCorrection > correction) [noexcept]
Definition at line 7 of file GaussianFilter.cpp.
GaussianFilter() [2/2]
GaussianFilter::GaussianFilter (GaussianFilter && kf) [noexcept]
Definition at line 19 of file GaussianFilter.cpp.
 GaussianFilter()
GaussianFilter::~GaussianFilter () [virtual], [noexcept]
Definition at line 27 of file GaussianFilter.cpp.
Member Function Documentation
boot()
bool FilteringAlgorithm::boot () [inherited]
Definition at line 8 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::filtering_thread_, and bfl::FilteringAlgorithm::filteringRecursion().
disable_log()
bool Logger::disable_log () [inherited]
Definition at line 58 of file Logger.cpp.
References bfl::Logger::file_names_, bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
Referenced by bfl::Logger::~Logger().
enable_log()
bool Logger::enable_log (const std::string & prefix_path, const std::string & prefix_name) [inherited]
Definition at line 15 of file Logger.cpp.
References bfl::Logger::file_names_, bfl::Logger::log_enabled_, bfl::Logger::log_filenames(), and bfl::Logger::log_files_.
filteringStep()
void GaussianFilter::filteringStep () [override], [virtual]
Implements bfl::FilteringAlgorithm.
Definition at line 37 of file GaussianFilter.cpp.
References corrected_state_, correction_, bfl::Logger::log(), predicted_state_, and prediction_.
get_prefix_name()
std::string Logger::get_prefix_name () const [inherited]
Definition at line 81 of file Logger.cpp.
References bfl::Logger::prefix_name_.
get_prefix_path()
std::string Logger::get_prefix_path () const [inherited]
Definition at line 75 of file Logger.cpp.
References bfl::Logger::prefix_path_.
getFilteringStep()
unsigned int FilteringAlgorithm::getFilteringStep () [inherited]
Definition at line 83 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::filtering_step_.
initialization()
bool GaussianFilter::initialization () [override], [virtual]
Implements bfl::FilteringAlgorithm.
Definition at line 31 of file GaussianFilter.cpp.
isRunning()
bool FilteringAlgorithm::isRunning () [inherited]
Definition at line 89 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::run_.
log()
void Logger::log () [protected], [virtual], [inherited]
Reimplemented in bfl::SIS, bfl::SimulatedStateModel, and bfl::SimulatedLinearSensor.
Definition at line 99 of file Logger.cpp.
Referenced by filteringStep().
log_filenames()
std::vector< std::string > Logger::log_filenames (const std::string & prefix_path, const std::string & prefix_name) [protected], [virtual], [inherited]
Reimplemented in bfl::LinearModel, bfl::SimulatedStateModel, and bfl::SIS.
Definition at line 87 of file Logger.cpp.
Referenced by bfl::Logger::enable_log().
logger() [1/4]
template<typename DatumType >
void bfl::Logger::logger (DatumType datum) [inline], [inherited]
Definition at line 28 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
Referenced by bfl::SimulatedLinearSensor::log().
logger() [2/4]
template<typename... DataType>
void bfl::Logger::logger (DataType... data) [inline], [inherited]
Definition at line 35 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::logger_helper().
logger() [3/4]
template<typename DatumType >
void bfl::Logger::logger (DatumType datum) const [inline], [inherited]
Definition at line 42 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
logger() [4/4]
template<typename... DataType>
void bfl::Logger::logger (DataType... data) const [inline], [inherited]
Definition at line 49 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::logger_helper().
operator=()
GaussianFilter& bfl::GaussianFilter::operator= (GaussianFilter && gf) [noexcept]
reboot()
void FilteringAlgorithm::reboot () [inherited]
Definition at line 66 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::cv_run_, bfl::FilteringAlgorithm::mtx_run_, bfl::FilteringAlgorithm::reset_, and bfl::FilteringAlgorithm::run_.
reset()
void FilteringAlgorithm::reset () [inherited]
Definition at line 60 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::reset_.
run()
void FilteringAlgorithm::run () [inherited]
Definition at line 26 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::cv_run_, bfl::FilteringAlgorithm::mtx_run_, and bfl::FilteringAlgorithm::run_.
runCondition()
bool GaussianFilter::runCondition () [override], [virtual]
Implements bfl::FilteringAlgorithm.
Definition at line 46 of file GaussianFilter.cpp.
skip()
bool GaussianFilter::skip (const std::string & what_step, const bool status) [override], [virtual]
Implements bfl::FilteringAlgorithm.
Definition at line 52 of file GaussianFilter.cpp.
References correction_, and prediction_.
teardown()
bool FilteringAlgorithm::teardown () [inherited]
Definition at line 75 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::teardown_.
wait()
bool FilteringAlgorithm::wait () [inherited]
Definition at line 34 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::filtering_thread_.
Member Data Documentation
corrected_state_
Gaussian bfl::GaussianFilter::corrected_state_ [protected]
Definition at line 36 of file GaussianFilter.h.
Referenced by filteringStep().
correction_
std::unique_ptr<GaussianCorrection> bfl::GaussianFilter::correction_ [protected]
Definition at line 40 of file GaussianFilter.h.
Referenced by filteringStep(), and skip().
predicted_state_
Gaussian bfl::GaussianFilter::predicted_state_ [protected]
Definition at line 34 of file GaussianFilter.h.
Referenced by filteringStep().
prediction_
std::unique_ptr<GaussianPrediction> bfl::GaussianFilter::prediction_ [protected]
Definition at line 38 of file GaussianFilter.h.
Referenced by filteringStep(), and skip().
The documentation for this class was generated from the following files:
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/include/BayesFilters/GaussianFilter.h
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/src/GaussianFilter.cpp