bfl::FilteringAlgorithm Class Reference
#include <FilteringAlgorithm.h>
Public Member Functions
virtual ~FilteringAlgorithm () noexcept
bool boot ()
void run ()
bool wait ()
void reset ()
void reboot ()
bool teardown ()
unsigned int getFilteringStep ()
bool isRunning ()
virtual bool skip (const std::string &what_step, const bool status)=0
bool enable_log (const std::string &prefix_path, const std::string &prefix_name)
bool disable_log ()
std::string get_prefix_path () const
std::string get_prefix_name () const
template<typename DatumType >
void logger (DatumType datum)
template<typename... DataType>
void logger (DataType... data)
template<typename DatumType >
void logger (DatumType datum) const
template<typename... DataType>
void logger (DataType... data) const
Protected Member Functions
virtual bool initialization ()=0
virtual void filteringStep ()=0
virtual bool runCondition ()=0
virtual std::vector< std::string > log_filenames (const std::string &prefix_path, const std::string &prefix_name)
virtual void log ()
Private Member Functions
void filteringRecursion ()
Private Attributes
unsigned int filtering_step_ = 0
std::thread filtering_thread_
std::mutex mtx_run_
std::condition_variable cv_run_
bool run_ = false
bool reset_ = false
bool teardown_ = false
Detailed Description
Definition at line 20 of file FilteringAlgorithm.h.
Constructor & Destructor Documentation
 FilteringAlgorithm()
virtual bfl::FilteringAlgorithm::~FilteringAlgorithm () [inline], [virtual], [noexcept]
Definition at line 23 of file FilteringAlgorithm.h.
Member Function Documentation
boot()
bool FilteringAlgorithm::boot ()
Definition at line 8 of file FilteringAlgorithm.cpp.
References filtering_thread_, and filteringRecursion().
disable_log()
bool Logger::disable_log () [inherited]
Definition at line 58 of file Logger.cpp.
References bfl::Logger::file_names_, bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
Referenced by bfl::Logger::~Logger().
enable_log()
bool Logger::enable_log (const std::string & prefix_path, const std::string & prefix_name) [inherited]
Definition at line 15 of file Logger.cpp.
References bfl::Logger::file_names_, bfl::Logger::log_enabled_, bfl::Logger::log_filenames(), and bfl::Logger::log_files_.
filteringRecursion()
void FilteringAlgorithm::filteringRecursion () [private]
Definition at line 95 of file FilteringAlgorithm.cpp.
References cv_run_, filtering_step_, filteringStep(), initialization(), mtx_run_, reset_, run_, runCondition(), and teardown_.
Referenced by boot().
filteringStep()
virtual void bfl::FilteringAlgorithm::filteringStep () [protected], [pure virtual]
Implemented in bfl::SIS, bfl::GaussianFilter, and bfl::UnscentedKalmanFilter.
Referenced by filteringRecursion().
get_prefix_name()
std::string Logger::get_prefix_name () const [inherited]
Definition at line 81 of file Logger.cpp.
References bfl::Logger::prefix_name_.
get_prefix_path()
std::string Logger::get_prefix_path () const [inherited]
Definition at line 75 of file Logger.cpp.
References bfl::Logger::prefix_path_.
getFilteringStep()
unsigned int FilteringAlgorithm::getFilteringStep ()
Definition at line 83 of file FilteringAlgorithm.cpp.
References filtering_step_.
initialization()
virtual bool bfl::FilteringAlgorithm::initialization () [protected], [pure virtual]
Implemented in bfl::SIS, bfl::GaussianFilter, and bfl::UnscentedKalmanFilter.
Referenced by filteringRecursion().
isRunning()
bool FilteringAlgorithm::isRunning ()
Definition at line 89 of file FilteringAlgorithm.cpp.
References run_.
log()
void Logger::log () [protected], [virtual], [inherited]
Reimplemented in bfl::SIS, bfl::SimulatedStateModel, and bfl::SimulatedLinearSensor.
Definition at line 99 of file Logger.cpp.
Referenced by bfl::GaussianFilter::filteringStep().
log_filenames()
std::vector< std::string > Logger::log_filenames (const std::string & prefix_path, const std::string & prefix_name) [protected], [virtual], [inherited]
Reimplemented in bfl::LinearModel, bfl::SimulatedStateModel, and bfl::SIS.
Definition at line 87 of file Logger.cpp.
Referenced by bfl::Logger::enable_log().
logger() [1/4]
template<typename DatumType >
void bfl::Logger::logger (DatumType datum) [inline], [inherited]
Definition at line 28 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
Referenced by bfl::SimulatedLinearSensor::log().
logger() [2/4]
template<typename... DataType>
void bfl::Logger::logger (DataType... data) [inline], [inherited]
Definition at line 35 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::logger_helper().
logger() [3/4]
template<typename DatumType >
void bfl::Logger::logger (DatumType datum) const [inline], [inherited]
Definition at line 42 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
logger() [4/4]
template<typename... DataType>
void bfl::Logger::logger (DataType... data) const [inline], [inherited]
Definition at line 49 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::logger_helper().
reboot()
void FilteringAlgorithm::reboot ()
Definition at line 66 of file FilteringAlgorithm.cpp.
References cv_run_, mtx_run_, reset_, and run_.
reset()
void FilteringAlgorithm::reset ()
Definition at line 60 of file FilteringAlgorithm.cpp.
References reset_.
run()
void FilteringAlgorithm::run ()
Definition at line 26 of file FilteringAlgorithm.cpp.
References cv_run_, mtx_run_, and run_.
runCondition()
virtual bool bfl::FilteringAlgorithm::runCondition () [protected], [pure virtual]
Implemented in bfl::SIS, and bfl::GaussianFilter.
Referenced by filteringRecursion().
skip()
virtual bool bfl::FilteringAlgorithm::skip (const std::string & what_step, const bool status) [pure virtual]
Implemented in bfl::GaussianFilter, and bfl::ParticleFilter.
teardown()
bool FilteringAlgorithm::teardown ()
Definition at line 75 of file FilteringAlgorithm.cpp.
References teardown_.
wait()
bool FilteringAlgorithm::wait ()
Definition at line 34 of file FilteringAlgorithm.cpp.
References filtering_thread_.
Member Data Documentation
cv_run_
std::condition_variable bfl::FilteringAlgorithm::cv_run_ [private]
Definition at line 59 of file FilteringAlgorithm.h.
Referenced by filteringRecursion(), reboot(), and run().
filtering_step_
unsigned int bfl::FilteringAlgorithm::filtering_step_ = 0 [private]
Definition at line 51 of file FilteringAlgorithm.h.
Referenced by filteringRecursion(), and getFilteringStep().
filtering_thread_
std::thread bfl::FilteringAlgorithm::filtering_thread_ [private]
Definition at line 53 of file FilteringAlgorithm.h.
Referenced by boot(), and wait().
mtx_run_
std::mutex bfl::FilteringAlgorithm::mtx_run_ [private]
Definition at line 57 of file FilteringAlgorithm.h.
Referenced by filteringRecursion(), reboot(), and run().
reset_
bool bfl::FilteringAlgorithm::reset_ = false [private]
Definition at line 63 of file FilteringAlgorithm.h.
Referenced by filteringRecursion(), reboot(), and reset().
run_
bool bfl::FilteringAlgorithm::run_ = false [private]
Definition at line 61 of file FilteringAlgorithm.h.
Referenced by filteringRecursion(), isRunning(), reboot(), and run().
teardown_
bool bfl::FilteringAlgorithm::teardown_ = false [private]
Definition at line 65 of file FilteringAlgorithm.h.
Referenced by filteringRecursion(), and teardown().
The documentation for this class was generated from the following files:
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/include/BayesFilters/FilteringAlgorithm.h
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/src/FilteringAlgorithm.cpp