bfl::MeasurementModelDecorator Class Reference
#include <MeasurementModelDecorator.h>
Public Member Functions
std::pair< bool, bfl::Data > measure () const override
std::pair< bool, bfl::Data > predictedMeasure (const Eigen::Ref< const Eigen::MatrixXd > &cur_states) const override
std::pair< bool, bfl::Data > innovation (const bfl::Data &predicted_measurements, const bfl::Data &measurements) const override
std::pair< bool, Eigen::MatrixXd > getNoiseCovarianceMatrix () const override
bool setProperty (const std::string &property) override
bool freezeMeasurements () override
std::pair< std::size_t, std::size_t > getOutputSize () const override
bool enable_log (const std::string &prefix_path, const std::string &prefix_name)
bool disable_log ()
std::string get_prefix_path () const
std::string get_prefix_name () const
template<typename DatumType >
void logger (DatumType datum)
template<typename... DataType>
void logger (DataType... data)
template<typename DatumType >
void logger (DatumType datum) const
template<typename... DataType>
void logger (DataType... data) const
Protected Member Functions
MeasurementModelDecorator (std::unique_ptr< MeasurementModel > measurement_model) noexcept
MeasurementModelDecorator (MeasurementModelDecorator &&measurement_model) noexcept
virtual ~MeasurementModelDecorator () noexcept
MeasurementModelDecorator & operator= (MeasurementModelDecorator &&measurement_model) noexcept
virtual std::vector< std::string > log_filenames (const std::string &prefix_path, const std::string &prefix_name)
virtual void log ()
Private Attributes
std::unique_ptr< MeasurementModel > measurement_model
Detailed Description
Definition at line 13 of file MeasurementModelDecorator.h.
Constructor & Destructor Documentation
MeasurementModelDecorator() [1/2]
MeasurementModelDecorator::MeasurementModelDecorator (std::unique_ptr< MeasurementModel > measurement_model) [protected], [noexcept]
Definition at line 7 of file MeasurementModelDecorator.cpp.
MeasurementModelDecorator() [2/2]
MeasurementModelDecorator::MeasurementModelDecorator (MeasurementModelDecorator && measurement_model) [protected], [noexcept]
Definition at line 11 of file MeasurementModelDecorator.cpp.
 MeasurementModelDecorator()
MeasurementModelDecorator::~MeasurementModelDecorator () [protected], [virtual], [noexcept]
Definition at line 15 of file MeasurementModelDecorator.cpp.
Member Function Documentation
disable_log()
bool Logger::disable_log () [inherited]
Definition at line 58 of file Logger.cpp.
References bfl::Logger::file_names_, bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
Referenced by bfl::Logger::~Logger().
enable_log()
bool Logger::enable_log (const std::string & prefix_path, const std::string & prefix_name) [inherited]
Definition at line 15 of file Logger.cpp.
References bfl::Logger::file_names_, bfl::Logger::log_enabled_, bfl::Logger::log_filenames(), and bfl::Logger::log_files_.
freezeMeasurements()
bool MeasurementModelDecorator::freezeMeasurements () [override], [virtual]
Implements bfl::MeasurementModel.
Definition at line 56 of file MeasurementModelDecorator.cpp.
get_prefix_name()
std::string Logger::get_prefix_name () const [inherited]
Definition at line 81 of file Logger.cpp.
References bfl::Logger::prefix_name_.
get_prefix_path()
std::string Logger::get_prefix_path () const [inherited]
Definition at line 75 of file Logger.cpp.
References bfl::Logger::prefix_path_.
getNoiseCovarianceMatrix()
std::pair< bool, MatrixXd > MeasurementModelDecorator::getNoiseCovarianceMatrix () const [override], [virtual]
Reimplemented from bfl::MeasurementModel.
Definition at line 44 of file MeasurementModelDecorator.cpp.
getOutputSize()
std::pair< std::size_t, std::size_t > MeasurementModelDecorator::getOutputSize () const [override], [virtual]
Implements bfl::MeasurementModel.
Definition at line 62 of file MeasurementModelDecorator.cpp.
innovation()
std::pair< bool, Data > MeasurementModelDecorator::innovation (const bfl::Data & predicted_measurements, const bfl::Data & measurements) const [override], [virtual]
Implements bfl::MeasurementModel.
Definition at line 38 of file MeasurementModelDecorator.cpp.
log()
void Logger::log () [protected], [virtual], [inherited]
Reimplemented in bfl::SIS, bfl::SimulatedStateModel, and bfl::SimulatedLinearSensor.
Definition at line 99 of file Logger.cpp.
Referenced by bfl::GaussianFilter::filteringStep().
log_filenames()
std::vector< std::string > Logger::log_filenames (const std::string & prefix_path, const std::string & prefix_name) [protected], [virtual], [inherited]
Reimplemented in bfl::LinearModel, bfl::SimulatedStateModel, and bfl::SIS.
Definition at line 87 of file Logger.cpp.
Referenced by bfl::Logger::enable_log().
logger() [1/4]
template<typename DatumType >
void bfl::Logger::logger (DatumType datum) [inline], [inherited]
Definition at line 28 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
Referenced by bfl::SimulatedLinearSensor::log().
logger() [2/4]
template<typename... DataType>
void bfl::Logger::logger (DataType... data) [inline], [inherited]
Definition at line 35 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::logger_helper().
logger() [3/4]
template<typename DatumType >
void bfl::Logger::logger (DatumType datum) const [inline], [inherited]
Definition at line 42 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::log_files_.
logger() [4/4]
template<typename... DataType>
void bfl::Logger::logger (DataType... data) const [inline], [inherited]
Definition at line 49 of file Logger.h.
References bfl::Logger::log_enabled_, and bfl::Logger::logger_helper().
measure()
std::pair< bool, Data > MeasurementModelDecorator::measure () const [override], [virtual]
Implements bfl::MeasurementModel.
Definition at line 26 of file MeasurementModelDecorator.cpp.
operator=()
MeasurementModelDecorator & MeasurementModelDecorator::operator= (MeasurementModelDecorator && measurement_model) [protected], [noexcept]
Definition at line 18 of file MeasurementModelDecorator.cpp.
predictedMeasure()
std::pair< bool, Data > MeasurementModelDecorator::predictedMeasure (const Eigen::Ref< const Eigen::MatrixXd > & cur_states) const [override], [virtual]
Implements bfl::MeasurementModel.
Definition at line 32 of file MeasurementModelDecorator.cpp.
setProperty()
bool MeasurementModelDecorator::setProperty (const std::string & property) [override], [virtual]
Reimplemented from bfl::MeasurementModel.
Definition at line 50 of file MeasurementModelDecorator.cpp.
Member Data Documentation
measurement_model
std::unique_ptr<MeasurementModel> bfl::MeasurementModelDecorator::measurement_model [private]
Definition at line 40 of file MeasurementModelDecorator.h.
The documentation for this class was generated from the following files:
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/include/BayesFilters/MeasurementModelDecorator.h
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/src/MeasurementModelDecorator.cpp