bfl::KFCorrection Class Reference
#include <KFCorrection.h>
Public Member Functions
KFCorrection (std::unique_ptr< LinearMeasurementModel > measurement_model) noexcept
KFCorrection (KFCorrection &&kf_prediction) noexcept
virtual ~KFCorrection () noexcept
MeasurementModel & getMeasurementModel () override
void correct (const GaussianMixture &pred_state, GaussianMixture &corr_state)
bool skip (const bool status)
virtual std::pair< bool, Eigen::VectorXd > getLikelihood ()
Protected Member Functions
void correctStep (const GaussianMixture &pred_state, GaussianMixture &corr_state) override
std::pair< bool, Eigen::VectorXd > likelihood (const Eigen::Ref< const Eigen::MatrixXd > &innovations)
Private Attributes
std::unique_ptr< LinearMeasurementModel > measurement_model_
Detailed Description
Definition at line 15 of file KFCorrection.h.
Constructor & Destructor Documentation
KFCorrection() [1/2]
KFCorrection::KFCorrection (std::unique_ptr< LinearMeasurementModel > measurement_model) [noexcept]
Definition at line 7 of file KFCorrection.cpp.
KFCorrection() [2/2]
KFCorrection::KFCorrection (KFCorrection && kf_prediction) [noexcept]
Definition at line 12 of file KFCorrection.cpp.
 KFCorrection()
KFCorrection::~KFCorrection () [virtual], [noexcept]
Definition at line 17 of file KFCorrection.cpp.
Member Function Documentation
correct()
void GaussianCorrection::correct (const GaussianMixture & pred_state, GaussianMixture & corr_state) [inherited]
Definition at line 10 of file GaussianCorrection.cpp.
correctStep()
void KFCorrection::correctStep (const GaussianMixture & pred_state, GaussianMixture & corr_state) [override], [protected], [virtual]
Implements bfl::GaussianCorrection.
Definition at line 27 of file KFCorrection.cpp.
References bfl::any::any_cast(), bfl::GaussianMixture::components, bfl::GaussianMixture::covariance(), and bfl::GaussianMixture::mean().
getLikelihood()
std::pair< bool, VectorXd > GaussianCorrection::getLikelihood () [virtual], [inherited]
Definition at line 20 of file GaussianCorrection.cpp.
getMeasurementModel()
MeasurementModel & KFCorrection::getMeasurementModel () [override], [virtual]
Implements bfl::GaussianCorrection.
Definition at line 21 of file KFCorrection.cpp.
likelihood()
std::pair< bool, Eigen::VectorXd > KFCorrection::likelihood (const Eigen::Ref< const Eigen::MatrixXd > & innovations) [protected], [virtual]
Implements bfl::GaussianCorrection.
Definition at line 99 of file KFCorrection.cpp.
skip()
bool GaussianCorrection::skip (const bool status) [inherited]
Definition at line 26 of file GaussianCorrection.cpp.
Member Data Documentation
measurement_model_
std::unique_ptr<LinearMeasurementModel> bfl::KFCorrection::measurement_model_ [private]
Definition at line 32 of file KFCorrection.h.
The documentation for this class was generated from the following files:
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/include/BayesFilters/KFCorrection.h
/Users/Claudio/GitHub/bayes-filters-lib/src/BayesFilters/src/KFCorrection.cpp