bfl::any Namespace Reference
Classes
class any
The class any describes a type-safe container for single values of any type.
class bad_any_cast
Defines a type of object to be thrown by the value-returning forms of libanyboost::any_cast on failure.
Functions
void swap (any &lhs, any &rhs) noexcept
Overloads the std::swap algorithm for std::any.
template<typename ValueType >
ValueType * any_cast (any *operand) noexcept
Performs type-safe access to the contained object.
template<typename ValueType >
const ValueType * any_cast (const any *operand) noexcept
Performs type-safe access to the contained object.
template<typename ValueType >
ValueType any_cast (any &operand)
Performs type-safe access to the contained object.
template<typename ValueType >
ValueType any_cast (const any &operand)
Performs type-safe access to the contained object.
template<typename ValueType >
ValueType any_cast (any &&operand)
Performs type-safe access to the contained object.
Function Documentation
any_cast() [1/5]
template<typename ValueType >
ValueType* bfl::any::any_cast (any * operand) [noexcept]
Performs type-safe access to the contained object.
Throws libanyboost::bad_any_cast if the typeid of the requested ValueType does not match that of the contents of operand.
Parameters
operand target any object
Definition at line 322 of file any.h.
References bfl::any::any::holder< ValueType >::held.
Referenced by bfl::KFCorrection::correctStep(), bfl::UKFCorrection::correctStep(), bfl::SUKFCorrection::correctStep(), bfl::SimulatedLinearSensor::freezeMeasurements(), bfl::LinearMeasurementModel::innovation(), bfl::GaussianLikelihood::likelihood(), and bfl::sigma_point::unscented_transform().
any_cast() [2/5]
template<typename ValueType >
const ValueType* bfl::any::any_cast (const any * operand) [inline], [noexcept]
Performs type-safe access to the contained object.
Throws libanyboost::bad_any_cast if the typeid of the requested ValueType does not match that of the contents of operand.
Parameters
operand target any object
Definition at line 337 of file any.h.
References bfl::any::any::any_cast.
any_cast() [3/5]
template<typename ValueType >
ValueType bfl::any::any_cast (any & operand)
Performs type-safe access to the contained object.
Throws libanyboost::bad_any_cast if the typeid of the requested ValueType does not match that of the contents of operand.
Parameters
operand target any object
Definition at line 352 of file any.h.
References bfl::any::any::any_cast, and bfl::any::any::type().
any_cast() [4/5]
template<typename ValueType >
ValueType bfl::any::any_cast (const any & operand) [inline]
Performs type-safe access to the contained object.
Throws libanyboost::bad_any_cast if the typeid of the requested ValueType does not match that of the contents of operand.
Parameters
operand target any object
Definition at line 375 of file any.h.
References bfl::any::any::any_cast.
any_cast() [5/5]
template<typename ValueType >
ValueType bfl::any::any_cast (any && operand) [inline]
Performs type-safe access to the contained object.
Throws libanyboost::bad_any_cast if the typeid of the requested ValueType does not match that of the contents of operand.
Parameters
operand target any object
Definition at line 391 of file any.h.
References bfl::any::any::any_cast.
swap()
void bfl::any::swap (any & lhs, any & rhs) [inline], [noexcept]
Overloads the std::swap algorithm for std::any.
Swaps the content of two any objects by calling lhs.swap(rhs).
Parameters
lhs objects to swap
rhs objects to swap
Definition at line 287 of file any.h.
References bfl::any::any::swap().
Referenced by bfl::any::any::swap().