bfl::directional_statistics Namespace Reference
Functions
Eigen::MatrixXd directional_add (const Eigen::Ref< const Eigen::MatrixXd > &a, const Eigen::Ref< const Eigen::VectorXd > &b)
Eigen::MatrixXd directional_sub (const Eigen::Ref< const Eigen::MatrixXd > &a, const Eigen::Ref< const Eigen::VectorXd > &b)
Eigen::VectorXd directional_mean (const Eigen::Ref< const Eigen::MatrixXd > &a, const Eigen::Ref< const Eigen::VectorXd > &w)
Function Documentation
directional_add()
Eigen::MatrixXd bfl::directional_statistics::directional_add (const Eigen::Ref< const Eigen::MatrixXd > & a, const Eigen::Ref< const Eigen::VectorXd > & b)
Referenced by bfl::sigma_point::sigma_point().
directional_mean()
Eigen::VectorXd bfl::directional_statistics::directional_mean (const Eigen::Ref< const Eigen::MatrixXd > & a, const Eigen::Ref< const Eigen::VectorXd > & w)
Referenced by bfl::sigma_point::unscented_transform().
directional_sub()
Eigen::MatrixXd bfl::directional_statistics::directional_sub (const Eigen::Ref< const Eigen::MatrixXd > & a, const Eigen::Ref< const Eigen::VectorXd > & b)
Referenced by bfl::SUKFCorrection::correctStep(), and bfl::sigma_point::unscented_transform().