bfl::sigma_point Namespace Reference
Classes
struct UTWeight
Typedefs
using OutputSize = std::pair< std::size_t, std::size_t >
A FunctionEvaluation return.
using FunctionEvaluation = std::function< std::tuple< bool, bfl::Data, OutputSize >(const Eigen::Ref< const Eigen::MatrixXd > &)>
Functions
void unscented_weights (const std::size_t n, const double alpha, const double beta, const double kappa, Eigen::Ref< Eigen::VectorXd > weight_mean, Eigen::Ref< Eigen::VectorXd > weight_covariance, double &c)
Eigen::MatrixXd sigma_point (const GaussianMixture &state, const double c)
std::tuple< bool, GaussianMixture, Eigen::MatrixXd > unscented_transform (const GaussianMixture &input, const UTWeight &weight, FunctionEvaluation function)
std::pair< GaussianMixture, Eigen::MatrixXd > unscented_transform (const GaussianMixture &state, const UTWeight &weight, StateModel &state_model)
std::pair< GaussianMixture, Eigen::MatrixXd > unscented_transform (const GaussianMixture &state, const UTWeight &weight, StateModel &state_model, ExogenousModel &exogenous_model)
std::pair< GaussianMixture, Eigen::MatrixXd > unscented_transform (const GaussianMixture &state, const UTWeight &weight, AdditiveStateModel &state_model)
std::pair< GaussianMixture, Eigen::MatrixXd > unscented_transform (const GaussianMixture &state, const UTWeight &weight, AdditiveStateModel &state_model, ExogenousModel &exogenous_model)
std::pair< GaussianMixture, Eigen::MatrixXd > unscented_transform (const GaussianMixture &state, const UTWeight &weight, ExogenousModel &exogenous_model)
std::tuple< bool, GaussianMixture, Eigen::MatrixXd > unscented_transform (const GaussianMixture &state, const UTWeight &weight, MeasurementModel &meas_model)
std::tuple< bool, GaussianMixture, Eigen::MatrixXd > unscented_transform (const GaussianMixture &state, const UTWeight &weight, AdditiveMeasurementModel &meas_model)
Typedef Documentation
FunctionEvaluation
using bfl::sigma_point::FunctionEvaluation = typedef std::function<std::tuple<bool, bfl::Data, OutputSize>(const Eigen::Ref<const Eigen::MatrixXd>&)>
Definition at line 28 of file sigma_point.h.
OutputSize
using bfl::sigma_point::OutputSize = typedef std::pair<std::size_t, std::size_t>
A FunctionEvaluation return.
a boolean indicating if the evaluation was successful
the output data in the form of bfl::Data
the output size as a pair of std::size_t indicating linear and circular size
Definition at line 27 of file sigma_point.h.
Function Documentation
sigma_point()
MatrixXd bfl::sigma_point::sigma_point (const GaussianMixture & state, const double c)
Definition at line 57 of file sigma_point.cpp.
References bfl::GaussianMixture::components, bfl::GaussianMixture::covariance(), bfl::GaussianMixture::dim, bfl::GaussianMixture::dim_circular, bfl::GaussianMixture::dim_linear, bfl::GaussianMixture::dim_noise, bfl::directional_statistics::directional_add(), and bfl::GaussianMixture::mean().
Referenced by bfl::SUKFCorrection::correctStep(), and unscented_transform().
unscented_transform() [1/8]
std::tuple< bool, GaussianMixture, MatrixXd > bfl::sigma_point::unscented_transform (const GaussianMixture & input, const UTWeight & weight, FunctionEvaluation function)
Definition at line 86 of file sigma_point.cpp.
References bfl::any::any_cast(), bfl::sigma_point::UTWeight::c, bfl::GaussianMixture::components, bfl::sigma_point::UTWeight::covariance, bfl::GaussianMixture::dim, bfl::GaussianMixture::dim_circular, bfl::GaussianMixture::dim_linear, bfl::directional_statistics::directional_mean(), bfl::directional_statistics::directional_sub(), bfl::GaussianMixture::mean(), bfl::sigma_point::UTWeight::mean, and sigma_point().
Referenced by bfl::UKFCorrection::correctStep(), bfl::UKFPrediction::predictStep(), and unscented_transform().
unscented_transform() [2/8]
std::pair< GaussianMixture, MatrixXd > bfl::sigma_point::unscented_transform (const GaussianMixture & state, const UTWeight & weight, StateModel & state_model)
Definition at line 143 of file sigma_point.cpp.
References bfl::StateModel::getOutputSize(), bfl::StateModel::motion(), and unscented_transform().
unscented_transform() [3/8]
std::pair< GaussianMixture, MatrixXd > bfl::sigma_point::unscented_transform (const GaussianMixture & state, const UTWeight & weight, StateModel & state_model, ExogenousModel & exogenous_model)
Definition at line 166 of file sigma_point.cpp.
References bfl::StateModel::getOutputSize(), bfl::StateModel::motion(), bfl::ExogenousModel::propagate(), and unscented_transform().
unscented_transform() [4/8]
std::pair< GaussianMixture, MatrixXd > bfl::sigma_point::unscented_transform (const GaussianMixture & state, const UTWeight & weight, AdditiveStateModel & state_model)
Definition at line 194 of file sigma_point.cpp.
References bfl::GaussianMixture::components, bfl::GaussianMixture::covariance(), bfl::StateModel::getNoiseCovarianceMatrix(), bfl::StateModel::getOutputSize(), bfl::StateModel::propagate(), and unscented_transform().
unscented_transform() [5/8]
std::pair< GaussianMixture, MatrixXd > bfl::sigma_point::unscented_transform (const GaussianMixture & state, const UTWeight & weight, AdditiveStateModel & state_model, ExogenousModel & exogenous_model)
Definition at line 223 of file sigma_point.cpp.
References bfl::GaussianMixture::components, bfl::GaussianMixture::covariance(), bfl::StateModel::getNoiseCovarianceMatrix(), bfl::StateModel::getOutputSize(), bfl::ExogenousModel::propagate(), bfl::StateModel::propagate(), and unscented_transform().
unscented_transform() [6/8]
std::pair< GaussianMixture, MatrixXd > bfl::sigma_point::unscented_transform (const GaussianMixture & state, const UTWeight & weight, ExogenousModel & exogenous_model)
Definition at line 258 of file sigma_point.cpp.
References bfl::ExogenousModel::getOutputSize(), bfl::ExogenousModel::propagate(), and unscented_transform().
unscented_transform() [7/8]
std::tuple< bool, GaussianMixture, MatrixXd > bfl::sigma_point::unscented_transform (const GaussianMixture & state, const UTWeight & weight, MeasurementModel & meas_model)
Definition at line 283 of file sigma_point.cpp.
References bfl::MeasurementModel::getOutputSize(), bfl::MeasurementModel::predictedMeasure(), and unscented_transform().
unscented_transform() [8/8]
std::tuple< bool, GaussianMixture, MatrixXd > bfl::sigma_point::unscented_transform (const GaussianMixture & state, const UTWeight & weight, AdditiveMeasurementModel & meas_model)
Definition at line 309 of file sigma_point.cpp.
References bfl::GaussianMixture::components, bfl::GaussianMixture::covariance(), bfl::MeasurementModel::getNoiseCovarianceMatrix(), bfl::MeasurementModel::getOutputSize(), bfl::MeasurementModel::predictedMeasure(), and unscented_transform().
unscented_weights()
void bfl::sigma_point::unscented_weights (const std::size_t n, const double alpha, const double beta, const double kappa, Eigen::Ref< Eigen::VectorXd > weight_mean, Eigen::Ref< Eigen::VectorXd > weight_covariance, double & c)
Referenced by bfl::sigma_point::UTWeight::UTWeight().